
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Dec  6 2024 10:09:03 WET (Dec  6 2024 10:09:03 UTC)

// Verification Directory fv/counter4bit 

module counter4bit(clk, enable, count_dir, reset, count);
  input clk, enable, count_dir, reset;
  output [3:0] count;
  wire clk, enable, count_dir, reset;
  wire [3:0] count;
  wire \count[0]_45 , \count[1]_46 , n_0, n_1, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20;
  QDFFKHD \count_reg[3] (.CK (clk), .D (n_20), .Q (count[3]));
  QDFFKHD \count_reg[2] (.CK (clk), .D (n_19), .Q (count[2]));
  OAI13BHD g497__2398(.A1 (n_17), .B1 (n_12), .B2 (count[3]), .B3
       (n_18), .O (n_20));
  OAI13BHD g500__5107(.A1 (n_15), .B1 (n_8), .B2 (count[2]), .B3
       (n_18), .O (n_19));
  QDFFEHD \count_reg[1] (.CK (clk), .D (n_16), .Q (\count[1]_46 ));
  OAI12CHD g499__6260(.A1 (count[3]), .B1 (n_13), .B2 (n_14), .O
       (n_17));
  OAI12CHD g502__4319(.A1 (n_11), .B1 (n_4), .B2 (n_18), .O (n_16));
  OAI12CHD g501__8428(.A1 (count[2]), .B1 (n_9), .B2 (n_14), .O (n_15));
  AN2B1CHD g503__5526(.I1 (n_12), .B1 (reset), .O (n_13));
  OAI12CHD g504__6783(.A1 (count[1]), .B1 (n_7), .B2 (n_14), .O (n_11));
  QDFFEHD \count_reg[0] (.CK (clk), .D (n_3), .Q (\count[0]_45 ));
  AN2B1CHD g506__3680(.I1 (n_8), .B1 (reset), .O (n_9));
  MXL2CHD g507__1617(.S (count[2]), .A (n_5), .B (n_6), .OB (n_12));
  MUXB2CHD g508__2802(.S (count_dir), .A (\count[0]_45 ), .B (n_1), .EB
       (reset), .O (n_7));
  NR2CHD g509__1705(.I1 (n_6), .I2 (n_5), .O (n_8));
  AOI13BHD g510__5122(.A1 (n_5), .B1 (n_0), .B2 (\count[0]_45 ), .B3
       (count_dir), .O (n_4));
  MOAI1CHD g511__8246(.A1 (count[0]), .A2 (n_18), .B1 (\count[0]_45 ),
       .B2 (n_14), .O (n_3));
  AN3EHD g512__7098(.I1 (\count[1]_46 ), .I2 (\count[0]_45 ), .I3
       (count_dir), .O (n_6));
  NR3BHD g513__6131(.I1 (count_dir), .I2 (\count[1]_46 ), .I3
       (\count[0]_45 ), .O (n_5));
  OR2B1CHD g514__1881(.I1 (reset), .B1 (enable), .O (n_18));
  NR2BHD g515__5115(.I1 (reset), .I2 (enable), .O (n_14));
  INVDHD g519(.I (\count[0]_45 ), .O (n_1));
  INVDHD g516(.I (\count[1]_46 ), .O (n_0));
  BUFHHD g517(.I (\count[1]_46 ), .O (count[1]));
  BUFHHD g518(.I (\count[0]_45 ), .O (count[0]));
endmodule

