
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Jan  7 2025 14:08:40 WET (Jan  7 2025 14:08:40 UTC)

// Verification Directory fv/BATCHARGER_controller 

module BATCHARGER_controller(cc, tc, cv, imonen, vmonen, tmonen, vtok,
     vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax, tmax, iend,
     clk, rstz, dvdd, dgnd);
  input vtok, clk, rstz;
  input [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  output cc, tc, cv, imonen, vmonen, tmonen;
  inout dvdd, dgnd;
  wire vtok, clk, rstz;
  wire [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  wire cc, tc, cv, imonen, vmonen, tmonen;
  wire dvdd, dgnd;
  wire [2:0] current_state;
  wire [15:0] tpreset;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200;
  wire n_201, n_202, n_203, n_204, n_205, n_206, n_207, n_208;
  wire n_209, n_210, n_211, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_234, n_235, n_236, n_237, n_238, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_245, n_246, n_247, n_248;
  wire n_249, n_250;
  assign tmonen = imonen;
  assign vmonen = imonen;
  QDFFEHD \current_state_reg[0] (.CK (clk), .D (n_250), .Q
       (current_state[0]));
  DFCRBEHD \current_state_reg[1] (.CK (clk), .D (n_249), .RB (vtok), .Q
       (current_state[1]), .QB (UNCONNECTED));
  DFCRBEHD \current_state_reg[2] (.CK (clk), .D (n_247), .RB (rstz), .Q
       (current_state[2]), .QB (UNCONNECTED0));
  AN4CHD g1487__2398(.I1 (vtok), .I2 (rstz), .I3 (n_248), .I4 (n_244),
       .O (n_250));
  AO13EHD g1489__5107(.A1 (n_246), .B1 (n_245), .B2 (n_228), .B3
       (rstz), .O (n_249));
  OAI112BHD g1493__6260(.A1 (n_242), .B1 (current_state[2]), .C1
       (n_241), .C2 (current_state[0]), .O (n_248));
  AN4B1BHD g1488__4319(.I1 (n_237), .I2 (n_240), .I3 (vtok), .B1
       (n_105), .O (n_247));
  AN3EHD g1492__8428(.I1 (n_245), .I2 (n_236), .I3 (rstz), .O (n_246));
  OAI222BHD g1491__5526(.A1 (n_243), .A2 (n_235), .B1
       (current_state[1]), .B2 (n_227), .C1 (current_state[1]), .C2
       (n_243), .O (n_244));
  OR2B1CHD g1495__6783(.I1 (n_241), .B1 (n_230), .O (n_242));
  OAI22CHD g1506__3680(.A1 (n_238), .A2 (n_232), .B1
       (current_state[1]), .B2 (n_223), .O (n_240));
  OAI22CHD g1505__1617(.A1 (n_229), .A2 (n_239), .B1 (n_239), .B2
       (n_238), .O (n_245));
  OR2B1CHD g1494__2802(.I1 (n_130), .B1 (n_236), .O (n_237));
  OA112EHD g1510__1705(.A1 (n_226), .B1 (n_52), .C1 (n_215), .C2
       (n_180), .O (n_241));
  MOAI1CHD g1507__5122(.A1 (n_234), .A2 (current_state[0]), .B1
       (n_234), .B2 (current_state[0]), .O (n_235));
  OAI22CHD g1518__8246(.A1 (n_233), .A2 (n_231), .B1 (n_233), .B2
       (current_state[0]), .O (n_239));
  NR2BHD g1517__7098(.I1 (current_state[2]), .I2 (n_234), .O (n_232));
  AOI22BHD g1508__6131(.A1 (n_231), .A2 (n_230), .B1 (n_230), .B2
       (n_219), .O (n_236));
  ND2DHD g1512__1881(.I1 (n_228), .I2 (n_227), .O (n_229));
  MOAI1CHD g1522__5115(.A1 (n_225), .A2 (n_224), .B1 (n_225), .B2
       (n_224), .O (n_226));
  INVCKDHD g1528(.I (n_231), .O (n_234));
  AO2222CHD g1532__7482(.A1 (n_220), .A2 (n_214), .B1 (n_201), .B2
       (n_173), .C1 (n_169), .C2 (n_170), .D1 (n_213), .D2 (n_210), .O
       (n_231));
  AN4B1BHD g1521__4733(.I1 (n_221), .I2 (n_202), .I3 (n_223), .B1
       (n_178), .O (n_227));
  AOI112BHD g1546__6161(.A1 (n_218), .B1 (n_212), .C1 (n_206), .C2
       (n_217), .O (n_225));
  DFCLRBEHD \tpreset_reg[15] (.CK (clk), .D (tpreset[15]), .LD (n_194),
       .RB (n_222), .Q (UNCONNECTED1), .QB (tpreset[15]));
  DFCLRBEHD \tpreset_reg[13] (.CK (clk), .D (tpreset[13]), .LD (n_191),
       .RB (n_222), .Q (UNCONNECTED2), .QB (tpreset[13]));
  DFCLRBEHD \tpreset_reg[11] (.CK (clk), .D (tpreset[11]), .LD (n_196),
       .RB (n_222), .Q (UNCONNECTED3), .QB (tpreset[11]));
  NR2BHD g1535__9315(.I1 (n_177), .I2 (n_216), .O (n_221));
  OAI112BHD g1549__9945(.A1 (n_211), .B1 (n_208), .C1 (n_152), .C2
       (vbat[3]), .O (n_220));
  DFCLRBEHD \tpreset_reg[14] (.CK (clk), .D (tpreset[14]), .LD (n_197),
       .RB (n_222), .Q (UNCONNECTED4), .QB (tpreset[14]));
  AO2222BHD g1516__2883(.A1 (n_199), .A2 (n_139), .B1 (n_44), .B2
       (n_35), .C1 (n_134), .C2 (vbat[7]), .D1 (n_138), .D2 (n_141), .O
       (n_219));
  AO2222BHD g1519__2346(.A1 (n_203), .A2 (n_137), .B1 (n_42), .B2
       (n_37), .C1 (n_133), .C2 (vbat[7]), .D1 (n_136), .D2 (n_127), .O
       (n_230));
  DFCLRBEHD \tpreset_reg[9] (.CK (clk), .D (tpreset[9]), .LD (n_190),
       .RB (n_222), .Q (UNCONNECTED5), .QB (tpreset[9]));
  OA112EHD g1548__1666(.A1 (n_217), .B1 (n_189), .C1 (n_187), .C2
       (n_184), .O (n_218));
  DFCLRBEHD \tpreset_reg[10] (.CK (clk), .D (tpreset[10]), .LD (n_186),
       .RB (n_222), .Q (UNCONNECTED6), .QB (tpreset[10]));
  DFCLRBEHD \tpreset_reg[12] (.CK (clk), .D (tpreset[12]), .LD (n_181),
       .RB (n_222), .Q (UNCONNECTED7), .QB (tpreset[12]));
  AN4B1BHD g1553__7410(.I1 (n_204), .I2 (n_120), .I3 (n_21), .B1
       (n_176), .O (n_216));
  AN4B1BHD g1520__6417(.I1 (n_200), .I2 (n_116), .I3 (n_23), .B1
       (n_179), .O (n_215));
  DFCLRBEHD \tpreset_reg[8] (.CK (clk), .D (tpreset[8]), .LD (n_174),
       .RB (n_222), .Q (UNCONNECTED8), .QB (tpreset[8]));
  AN3EHD g1562__5477(.I1 (n_213), .I2 (n_209), .I3 (n_175), .O (n_214));
  OAI222BHD g1575__2398(.A1 (n_162), .A2 (n_205), .B1 (n_158), .B2
       (n_155), .C1 (n_64), .C2 (n_65), .O (n_212));
  OAI112BHD g1580__5107(.A1 (n_207), .B1 (n_164), .C1 (n_182), .C2
       (n_168), .O (n_211));
  DFCLRBEHD \tpreset_reg[7] (.CK (clk), .D (tpreset[7]), .LD (n_148),
       .RB (n_222), .Q (UNCONNECTED9), .QB (tpreset[7]));
  MOAI1CHD g1579__6260(.A1 (n_157), .A2 (vbat[5]), .B1 (n_209), .B2
       (n_166), .O (n_210));
  DFCLRBEHD \tpreset_reg[5] (.CK (clk), .D (tpreset[5]), .LD (n_135),
       .RB (n_222), .Q (UNCONNECTED10), .QB (tpreset[5]));
  DFCLRBEHD \tpreset_reg[6] (.CK (clk), .D (tpreset[6]), .LD (n_142),
       .RB (n_222), .Q (UNCONNECTED11), .QB (tpreset[6]));
  OR3B1EHD g1597__4319(.I1 (vbat[2]), .I2 (n_163), .B1 (n_207), .O
       (n_208));
  OAI222BHD g1604__8428(.A1 (n_112), .A2 (n_188), .B1 (n_143), .B2
       (n_115), .C1 (n_103), .C2 (n_104), .O (n_206));
  AOI112BHD g1605__5526(.A1 (n_205), .B1 (n_161), .C1 (n_160), .C2
       (n_159), .O (n_217));
  OAI112BHD g1577__6783(.A1 (n_150), .B1 (n_81), .C1 (n_33), .C2
       (tbat[3]), .O (n_204));
  OAI112BHD g1524__3680(.A1 (n_149), .B1 (n_99), .C1 (n_198), .C2
       (vcutoff[3]), .O (n_203));
  AO13CHD g1554__1617(.A1 (n_123), .B1 (n_151), .B2 (n_58), .B3 (n_22),
       .O (n_202));
  AN2EHD g1581__2802(.I1 (n_201), .I2 (n_172), .O (n_213));
  DFCLRBEHD \tpreset_reg[4] (.CK (clk), .D (tpreset[4]), .LD (n_124),
       .RB (n_222), .Q (UNCONNECTED12), .QB (tpreset[4]));
  OAI112BHD g1525__1705(.A1 (n_145), .B1 (n_72), .C1 (n_40), .C2
       (iend[3]), .O (n_200));
  OAI112BHD g1526__5122(.A1 (n_144), .B1 (n_93), .C1 (n_198), .C2
       (vpreset[3]), .O (n_199));
  NR3BHD g1500__8246(.I1 (n_192), .I2 (n_193), .I3 (n_195), .O (n_197));
  NR3BHD g1499__7098(.I1 (tpreset[10]), .I2 (n_185), .I3 (n_195), .O
       (n_196));
  NR4EHD g1501__6131(.I1 (n_193), .I2 (n_195), .I3 (tpreset[14]), .I4
       (n_192), .O (n_194));
  NR3BHD g1502__1881(.I1 (tpreset[12]), .I2 (n_193), .I3 (n_195), .O
       (n_191));
  NR2BHD g1666__5115(.I1 (tpreset[8]), .I2 (n_195), .O (n_190));
  NR2CHD g1595__7482(.I1 (n_84), .I2 (n_188), .O (n_189));
  DFCLRBEHD \tpreset_reg[2] (.CK (clk), .D (tpreset[2]), .LD (n_86),
       .RB (n_222), .Q (UNCONNECTED13), .QB (tpreset[2]));
  DFCLRBEHD \tpreset_reg[3] (.CK (clk), .D (tpreset[3]), .LD (n_62),
       .RB (n_222), .Q (UNCONNECTED14), .QB (tpreset[3]));
  DFCLRBEHD \tpreset_reg[1] (.CK (clk), .D (tpreset[1]), .LD (n_128),
       .RB (n_222), .Q (UNCONNECTED15), .QB (tpreset[1]));
  AOI112BHD g1600__4733(.A1 (n_183), .B1 (n_75), .C1 (n_108), .C2
       (n_129), .O (n_187));
  NR2BHD g1496__6161(.I1 (n_185), .I2 (n_195), .O (n_186));
  OAI222BHD g1603__9315(.A1 (n_183), .A2 (n_113), .B1 (n_66), .B2
       (n_36), .C1 (n_59), .C2 (tpreset[6]), .O (n_184));
  AOI22BHD g1621__9945(.A1 (n_126), .A2 (vbat[0]), .B1 (n_167), .B2
       (vbat[1]), .O (n_182));
  NR2BHD g1497__2883(.I1 (n_193), .I2 (n_195), .O (n_181));
  DFCRBEHD \tpreset_reg[0] (.CK (clk), .D (n_222), .RB (tpreset[0]), .Q
       (UNCONNECTED16), .QB (tpreset[0]));
  OAI112BHD g1523__2346(.A1 (n_77), .B1 (n_25), .C1 (n_117), .C2
       (n_179), .O (n_180));
  OAI112BHD g1567__1666(.A1 (n_55), .B1 (n_28), .C1 (n_119), .C2
       (n_122), .O (n_178));
  OAI112BHD g1568__7410(.A1 (n_54), .B1 (n_24), .C1 (n_121), .C2
       (n_176), .O (n_177));
  ND2CHD g1582__6417(.I1 (n_165), .I2 (vbat[4]), .O (n_175));
  INVCKDHD g1669(.I (n_195), .O (n_174));
  NR2CHD g1587__5477(.I1 (vbat[6]), .I2 (n_171), .O (n_173));
  ND2CHD g1588__2398(.I1 (n_171), .I2 (vbat[6]), .O (n_172));
  OR2EHD g1593__5107(.I1 (n_170), .I2 (n_169), .O (n_201));
  NR2CHD g1607__6260(.I1 (vbat[1]), .I2 (n_167), .O (n_168));
  NR2CHD g1611__4319(.I1 (vbat[4]), .I2 (n_165), .O (n_166));
  ND2CHD g1609__8428(.I1 (n_163), .I2 (vbat[2]), .O (n_164));
  OA13EHD g1620__5526(.A1 (n_125), .B1 (n_161), .B2 (n_160), .B3
       (n_159), .O (n_162));
  OA13EHD g1640__6783(.A1 (n_111), .B1 (n_156), .B2 (n_154), .B3
       (n_153), .O (n_158));
  ND2CHD g1613__3680(.I1 (n_157), .I2 (vbat[5]), .O (n_209));
  AO112EHD g1625__1617(.A1 (n_156), .B1 (n_155), .C1 (n_154), .C2
       (n_153), .O (n_205));
  ND2CHD g1614__2802(.I1 (n_152), .I2 (vbat[3]), .O (n_207));
  OAI112BHD g1601__1705(.A1 (n_85), .B1 (n_57), .C1 (n_56), .C2
       (tbat[2]), .O (n_151));
  OAI112BHD g1602__5122(.A1 (n_78), .B1 (n_80), .C1 (n_79), .C2
       (tempmin[2]), .O (n_150));
  AO12CHD g1527__8246(.A1 (n_38), .B1 (n_101), .B2 (n_140), .O (n_223));
  OR3EHD g1670__7098(.I1 (n_43), .I2 (n_147), .I3 (n_146), .O (n_195));
  OAI112BHD g1544__6131(.A1 (n_87), .B1 (n_98), .C1 (n_97), .C2
       (vbat[2]), .O (n_149));
  NR3BHD g1503__1881(.I1 (tpreset[6]), .I2 (n_147), .I3 (n_146), .O
       (n_148));
  OAI112BHD g1542__5115(.A1 (n_76), .B1 (n_71), .C1 (n_70), .C2
       (ibat[2]), .O (n_145));
  OAI112BHD g1545__7482(.A1 (n_102), .B1 (n_92), .C1 (n_91), .C2
       (vbat[2]), .O (n_144));
  AO12EHD g1641__4733(.A1 (n_143), .B1 (n_114), .B2 (tpreset[8]), .O
       (n_188));
  NR2BHD g1498__6161(.I1 (n_147), .I2 (n_146), .O (n_142));
  OAI12CHD g1541__9315(.A1 (n_96), .B1 (n_140), .B2 (vpreset[5]), .O
       (n_141));
  OA112CHD g1529__9945(.A1 (n_138), .B1 (n_95), .C1 (n_94), .C2
       (vbat[4]), .O (n_139));
  OA112CHD g1530__2883(.A1 (n_136), .B1 (n_89), .C1 (n_88), .C2
       (vbat[4]), .O (n_137));
  NR2BHD g1667__2346(.I1 (tpreset[4]), .I2 (n_146), .O (n_135));
  OAI22CHD g1624__1666(.A1 (n_134), .A2 (n_131), .B1 (n_132), .B2
       (n_133), .O (n_169));
  AOI22BHD g1623__7410(.A1 (n_132), .A2 (vpreset[6]), .B1 (n_131), .B2
       (vcutoff[6]), .O (n_171));
  AN4B1BHD g1490__6417(.I1 (n_130), .I2 (vtok), .I3 (rstz), .B1
       (n_238), .O (n_222));
  OR3B2CHD g1638__5477(.I1 (n_69), .B1 (n_128), .B2 (tmax[0]), .O
       (n_129));
  OAI12CHD g1543__2398(.A1 (n_90), .B1 (n_140), .B2 (vcutoff[5]), .O
       (n_127));
  AOI22BHD g1653__5107(.A1 (n_132), .A2 (vpreset[0]), .B1 (n_131), .B2
       (vcutoff[0]), .O (n_126));
  AOI22BHD g1643__6260(.A1 (n_132), .A2 (vpreset[4]), .B1 (n_131), .B2
       (vcutoff[4]), .O (n_165));
  AOI22BHD g1644__4319(.A1 (n_132), .A2 (vpreset[2]), .B1 (n_131), .B2
       (vcutoff[2]), .O (n_163));
  AOI22BHD g1645__8428(.A1 (n_132), .A2 (vpreset[3]), .B1 (n_131), .B2
       (vcutoff[3]), .O (n_152));
  AOI22BHD g1642__5526(.A1 (n_132), .A2 (vpreset[5]), .B1 (n_131), .B2
       (vcutoff[5]), .O (n_157));
  AOI22BHD g1659__6783(.A1 (n_132), .A2 (vpreset[1]), .B1 (n_131), .B2
       (vcutoff[1]), .O (n_167));
  ND2DHD g1626__3680(.I1 (n_106), .I2 (n_107), .O (n_125));
  INVCKDHD g1671(.I (n_146), .O (n_124));
  OR3B2CHD g1578__1617(.I1 (n_122), .B1 (n_118), .B2 (n_19), .O
       (n_123));
  AOI22BHD g1596__2802(.A1 (n_14), .A2 (n_120), .B1 (n_34), .B2
       (tempmin[5]), .O (n_121));
  AOI22BHD g1599__1705(.A1 (n_15), .A2 (n_118), .B1 (n_9), .B2
       (tbat[5]), .O (n_119));
  AOI22BHD g1533__5122(.A1 (n_27), .A2 (n_116), .B1 (n_41), .B2
       (ibat[5]), .O (n_117));
  NR2CHD g1663__8246(.I1 (n_109), .I2 (n_110), .O (n_156));
  OR2EHD g1656__7098(.I1 (tpreset[8]), .I2 (n_114), .O (n_115));
  OA13EHD g1637__6131(.A1 (n_18), .B1 (n_74), .B2 (tpreset[3]), .B3
       (n_73), .O (n_113));
  AOI13BHD g1639__1881(.A1 (n_39), .B1 (n_83), .B2 (n_82), .B3
       (tmax[7]), .O (n_112));
  ND2DHD g1655__5115(.I1 (n_110), .I2 (n_109), .O (n_111));
  OA13EHD g1636__7482(.A1 (n_20), .B1 (n_68), .B2 (tpreset[1]), .B3
       (n_67), .O (n_108));
  NR2CHD g1658__4733(.I1 (n_107), .I2 (n_106), .O (n_161));
  AN2B1CHD g1509__6161(.I1 (n_238), .B1 (n_105), .O (n_243));
  AN2EHD g1657__9315(.I1 (n_104), .I2 (n_103), .O (n_143));
  MAO222CHD g1565__9945(.A1 (n_29), .B1 (n_3), .C1 (vbat[1]), .O
       (n_102));
  OAI22CHD g1558__2883(.A1 (vbat[3]), .A2 (n_16), .B1 (vbat[3]), .B2
       (vbat[2]), .O (n_101));
  NR2BHD g1477__2346(.I1 (n_51), .I2 (n_131), .O (cc));
  ND3CHD g1559__1666(.I1 (n_98), .I2 (n_97), .I3 (vbat[2]), .O (n_99));
  ND3CHD g1560__7410(.I1 (n_95), .I2 (n_94), .I3 (vbat[4]), .O (n_96));
  ND3CHD g1561__6417(.I1 (n_92), .I2 (n_91), .I3 (vbat[2]), .O (n_93));
  ND3CHD g1563__5477(.I1 (n_89), .I2 (n_88), .I3 (vbat[4]), .O (n_90));
  MAO222CHD g1564__2398(.A1 (n_31), .B1 (n_12), .C1 (vbat[1]), .O
       (n_87));
  OR3EHD g1511__5107(.I1 (tpreset[11]), .I2 (tpreset[10]), .I3 (n_185),
       .O (n_193));
  OR3B2CHD g1672__6260(.I1 (tpreset[3]), .B1 (n_86), .B2 (n_61), .O
       (n_146));
  MAO222CHD g1622__4319(.A1 (n_26), .B1 (n_11), .C1 (tbat[1]), .O
       (n_85));
  OAI12CHD g1617__8428(.A1 (n_83), .B1 (n_82), .B2 (tmax[7]), .O
       (n_84));
  ND3CHD g1618__5526(.I1 (n_80), .I2 (n_79), .I3 (tempmin[2]), .O
       (n_81));
  MAO222CHD g1619__6783(.A1 (n_17), .B1 (n_10), .C1 (tempmin[1]), .O
       (n_78));
  OR3B2CHD g1536__3680(.I1 (iend[6]), .B1 (n_47), .B2 (ibat[6]), .O
       (n_77));
  MAO222CHD g1566__1617(.A1 (n_30), .B1 (n_5), .C1 (ibat[1]), .O
       (n_76));
  AO12EHD g1629__2802(.A1 (n_74), .B1 (tpreset[3]), .B2 (n_73), .O
       (n_75));
  ND3CHD g1550__1705(.I1 (n_71), .I2 (n_70), .I3 (ibat[2]), .O (n_72));
  AO12EHD g1654__5122(.A1 (n_68), .B1 (tpreset[1]), .B2 (n_67), .O
       (n_69));
  AO12EHD g1635__8246(.A1 (n_66), .B1 (tpreset[5]), .B2 (n_60), .O
       (n_183));
  AN2EHD g1632__7098(.I1 (n_65), .I2 (n_64), .O (n_155));
  NR3BHD g1478__6131(.I1 (current_state[0]), .I2 (current_state[1]),
       .I3 (n_228), .O (cv));
  AN2EHD g1668__1881(.I1 (n_86), .I2 (n_61), .O (n_62));
  AOI22BHD g1684__5115(.A1 (tpreset[13]), .A2 (n_60), .B1 (n_4), .B2
       (tmax[5]), .O (n_154));
  AOI22BHD g1687__7482(.A1 (tpreset[9]), .A2 (n_67), .B1 (n_1), .B2
       (tmax[1]), .O (n_114));
  OAI22CHD g1688__4733(.A1 (tmax[6]), .A2 (n_2), .B1 (tpreset[14]), .B2
       (n_59), .O (n_110));
  MUX2EHD g1689__6161(.S (tmax[2]), .A (n_6), .B (tpreset[10]), .O
       (n_104));
  AOI22BHD g1686__9315(.A1 (tpreset[11]), .A2 (n_73), .B1 (n_7), .B2
       (tmax[3]), .O (n_160));
  MXL2CHD g1685__9945(.S (tmax[4]), .A (n_8), .B (tpreset[12]), .OB
       (n_106));
  OAI12CHD g1690__2883(.A1 (imonen), .B1 (current_state[2]), .B2
       (current_state[1]), .O (n_238));
  INVDHD g1664(.I (n_131), .O (n_132));
  ND3CHD g1616__2346(.I1 (n_57), .I2 (n_56), .I3 (tbat[2]), .O (n_58));
  ND3CHD g1598__1666(.I1 (n_46), .I2 (n_45), .I3 (tbat[6]), .O (n_55));
  ND3CHD g1594__7410(.I1 (n_50), .I2 (n_49), .I3 (tempmin[6]), .O
       (n_54));
  AN2CHD g1476__6417(.I1 (n_105), .I2 (current_state[1]), .O (tc));
  OAI22CHD g1531__5477(.A1 (current_state[1]), .A2 (n_52), .B1 (n_51),
       .B2 (current_state[0]), .O (n_233));
  OAI12CHD g1591__2398(.A1 (n_50), .B1 (n_49), .B2 (tempmin[6]), .O
       (n_176));
  AOI22BHD g1537__5107(.A1 (n_48), .A2 (vpreset[6]), .B1 (n_170), .B2
       (vpreset[7]), .O (n_138));
  AOI22BHD g1538__6260(.A1 (n_48), .A2 (vcutoff[6]), .B1 (n_170), .B2
       (vcutoff[7]), .O (n_136));
  OAI12CHD g1539__4319(.A1 (n_47), .B1 (n_0), .B2 (ibat[6]), .O
       (n_179));
  OAI12CHD g1592__8428(.A1 (n_46), .B1 (n_45), .B2 (tbat[6]), .O
       (n_122));
  ND2CHD g1555__5526(.I1 (n_170), .I2 (vpreset[7]), .O (n_44));
  OR2B1CHD g1674__6783(.I1 (tpreset[6]), .B1 (n_82), .O (n_43));
  ND2CHD g1557__3680(.I1 (n_170), .I2 (vcutoff[7]), .O (n_42));
  OR2CHD g1574__1617(.I1 (ibat[5]), .I2 (n_41), .O (n_116));
  ND2CHD g1569__2802(.I1 (n_40), .I2 (iend[3]), .O (n_71));
  NR2CHD g1662__1705(.I1 (tmax[4]), .I2 (n_13), .O (n_74));
  ND2CHD g1570__5122(.I1 (n_198), .I2 (vpreset[3]), .O (n_92));
  ND2CHD g1571__8246(.I1 (n_140), .I2 (vcutoff[5]), .O (n_89));
  ND2CHD g1572__7098(.I1 (n_198), .I2 (vcutoff[3]), .O (n_98));
  ND2CHD g1573__6131(.I1 (n_140), .I2 (vpreset[5]), .O (n_95));
  ND2DHD g1665__1881(.I1 (n_228), .I2 (current_state[0]), .O (n_131));
  NR2CHD g1646__5115(.I1 (tmax[0]), .I2 (n_32), .O (n_39));
  OAI112BHD g1540__7482(.A1 (vbat[7]), .B1 (vbat[6]), .C1 (vbat[5]),
       .C2 (vbat[4]), .O (n_38));
  NR2BHD g1551__4733(.I1 (vcutoff[6]), .I2 (n_48), .O (n_37));
  OR2EHD g1648__6161(.I1 (n_60), .I2 (tpreset[5]), .O (n_36));
  NR2BHD g1547__9315(.I1 (vpreset[6]), .I2 (n_48), .O (n_35));
  ND2CHD g1630__9945(.I1 (n_34), .I2 (tempmax[5]), .O (n_118));
  ND2CHD g1634__2883(.I1 (n_33), .I2 (tbat[3]), .O (n_80));
  AN2EHD g1652__2346(.I1 (tpreset[6]), .I2 (n_59), .O (n_66));
  OR2CHD g1631__1666(.I1 (tempmin[5]), .I2 (n_34), .O (n_120));
  ND2CHD g1660__7410(.I1 (n_32), .I2 (tmax[0]), .O (n_83));
  NR2CHD g1661__6417(.I1 (tmax[2]), .I2 (n_61), .O (n_68));
  XNR2EHD g1683__5477(.I1 (tmax[7]), .I2 (tpreset[15]), .O (n_65));
  OR2B1CHD g1583__2398(.I1 (vbat[0]), .B1 (vcutoff[0]), .O (n_31));
  OR2B1CHD g1586__5107(.I1 (ibat[0]), .B1 (iend[0]), .O (n_30));
  OR2B1CHD g1585__6260(.I1 (vbat[0]), .B1 (vpreset[0]), .O (n_29));
  OR2B1CHD g1584__4319(.I1 (tempmax[7]), .B1 (tbat[7]), .O (n_28));
  AN2B1CHD g1576__8428(.I1 (ibat[4]), .B1 (iend[4]), .O (n_27));
  OR2B1CHD g1650__5526(.I1 (tbat[0]), .B1 (tempmax[0]), .O (n_26));
  OR2EHD g1513__6783(.I1 (tpreset[13]), .I2 (tpreset[12]), .O (n_192));
  OR2EHD g1681__3680(.I1 (tmax[2]), .I2 (tpreset[10]), .O (n_159));
  ND2DHD g1504__1617(.I1 (current_state[0]), .I2 (current_state[2]), .O
       (n_130));
  OR2B1CHD g1556__2802(.I1 (ibat[7]), .B1 (iend[7]), .O (n_47));
  NR2CHD g1675__1705(.I1 (tmax[5]), .I2 (tpreset[13]), .O (n_109));
  OR2EHD g1679__5122(.I1 (tmax[7]), .I2 (tpreset[15]), .O (n_224));
  OR2EHD g1680__8246(.I1 (tmax[4]), .I2 (tpreset[12]), .O (n_153));
  NR2CHD g1677__7098(.I1 (tmax[3]), .I2 (tpreset[11]), .O (n_107));
  OR2EHD g1676__6131(.I1 (tmax[1]), .I2 (tpreset[9]), .O (n_103));
  OR2EHD g1514__1881(.I1 (tpreset[9]), .I2 (tpreset[8]), .O (n_185));
  NR2CHD g1682__5115(.I1 (tpreset[1]), .I2 (tpreset[0]), .O (n_86));
  NR2CHD g1515__7482(.I1 (current_state[2]), .I2 (current_state[0]), .O
       (n_105));
  OR2B1CHD g1534__4733(.I1 (iend[7]), .B1 (ibat[7]), .O (n_25));
  OR2B1CHD g1590__6161(.I1 (tbat[7]), .B1 (tempmin[7]), .O (n_24));
  OR2B1CHD g1552__9315(.I1 (ibat[4]), .B1 (iend[4]), .O (n_23));
  OR2B1CHD g1606__9945(.I1 (tempmax[3]), .B1 (tbat[3]), .O (n_22));
  OR2B1CHD g1608__2883(.I1 (tempmin[4]), .B1 (tbat[4]), .O (n_21));
  OR2B1CHD g1651__2346(.I1 (tpreset[2]), .B1 (tmax[2]), .O (n_20));
  OR2B1CHD g1610__1666(.I1 (tbat[4]), .B1 (tempmax[4]), .O (n_19));
  OR2B1CHD g1649__7410(.I1 (tpreset[4]), .B1 (tmax[4]), .O (n_18));
  OR2B1CHD g1647__6417(.I1 (tempmin[0]), .B1 (tbat[0]), .O (n_17));
  AN2CHD g1589__5477(.I1 (vbat[1]), .I2 (vbat[0]), .O (n_16));
  AN2B1CHD g1627__2398(.I1 (tbat[4]), .B1 (tempmax[4]), .O (n_15));
  AN2B1CHD g1628__5107(.I1 (tempmin[4]), .B1 (tbat[4]), .O (n_14));
  OR2B1CHD g1612__6260(.I1 (tbat[7]), .B1 (tempmax[7]), .O (n_46));
  OR2B1CHD g1615__4319(.I1 (tempmin[7]), .B1 (tbat[7]), .O (n_50));
  OR2B1CHD g1633__8428(.I1 (tbat[3]), .B1 (tempmax[3]), .O (n_57));
  OR2EHD g1678__5526(.I1 (tmax[6]), .I2 (tpreset[14]), .O (n_64));
  OR2EHD g1673__6783(.I1 (tpreset[5]), .I2 (tpreset[4]), .O (n_147));
  ND2DHD g1691__3680(.I1 (current_state[1]), .I2 (current_state[2]), .O
       (imonen));
  INVDHD g1732(.I (tpreset[4]), .O (n_13));
  INVCKDHD g1723(.I (vcutoff[1]), .O (n_12));
  INVCKDHD g1694(.I (tempmax[1]), .O (n_11));
  INVCKDHD g1700(.I (tbat[1]), .O (n_10));
  INVCKDHD g1693(.I (tempmax[5]), .O (n_9));
  INVCKDHD g1733(.I (tpreset[12]), .O (n_8));
  INVDHD g1730(.I (tpreset[11]), .O (n_7));
  INVCKDHD g1715(.I (tempmax[2]), .O (n_56));
  INVCKDHD g1720(.I (vpreset[4]), .O (n_94));
  INVCKDHD g1725(.I (tbat[2]), .O (n_79));
  INVCKDHD g1698(.I (vcutoff[7]), .O (n_133));
  INVCKDHD g1719(.I (ibat[3]), .O (n_40));
  INVDHD g1714(.I (current_state[0]), .O (n_52));
  INVCKDHD g1721(.I (vcutoff[4]), .O (n_88));
  INVCKDHD g1722(.I (vpreset[7]), .O (n_134));
  INVCKDHD g1717(.I (tempmax[6]), .O (n_45));
  INVCKDHD g1703(.I (tmax[5]), .O (n_60));
  INVCKDHD g1728(.I (tmax[1]), .O (n_67));
  INVCKDHD g1727(.I (tmax[3]), .O (n_73));
  INVCKDHD g1712(.I (vbat[3]), .O (n_198));
  INVCKDHD g1710(.I (vbat[6]), .O (n_48));
  INVDHD g1735(.I (current_state[2]), .O (n_228));
  INVCKDHD g1709(.I (tpreset[10]), .O (n_6));
  INVCKDHD g1692(.I (iend[1]), .O (n_5));
  INVDHD g1707(.I (tpreset[13]), .O (n_4));
  INVCKDHD g1724(.I (vpreset[1]), .O (n_3));
  INVCKDHD g1705(.I (tpreset[14]), .O (n_2));
  INVDHD g1706(.I (tpreset[9]), .O (n_1));
  INVCKDHD g1695(.I (iend[6]), .O (n_0));
  INVCKDHD g1696(.I (tempmin[3]), .O (n_33));
  INVDHD g1713(.I (current_state[1]), .O (n_51));
  INVCKDHD g1697(.I (vpreset[2]), .O (n_91));
  INVCKDHD g1711(.I (tpreset[8]), .O (n_32));
  INVCKDHD g1718(.I (iend[2]), .O (n_70));
  INVDHD g1729(.I (tpreset[0]), .O (n_128));
  INVCKDHD g1699(.I (vcutoff[2]), .O (n_97));
  INVCKDHD g1716(.I (iend[5]), .O (n_41));
  INVCKDHD g1702(.I (tbat[6]), .O (n_49));
  INVDHD g1704(.I (tpreset[7]), .O (n_82));
  INVCKDHD g1701(.I (tbat[5]), .O (n_34));
  INVDHD g1731(.I (tpreset[2]), .O (n_61));
  INVCKDHD g1726(.I (tmax[6]), .O (n_59));
  INVCKDHD g1734(.I (vbat[5]), .O (n_140));
  INVCKDHD g1708(.I (vbat[7]), .O (n_170));
endmodule

