
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Dec  9 2024 13:59:18 WET (Dec  9 2024 13:59:18 UTC)

// Verification Directory fv/BATCHARGER_controller 

module BATCHARGER_controller(cc, tc, cv, imonen, vmonen, tmonen, vtok,
     vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax, tmax, iend,
     clk, en, rstz, dvdd, dgnd, se, si, so);
  input vtok, clk, en, rstz, se, si;
  input [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  output cc, tc, cv, imonen, vmonen, tmonen, so;
  inout dvdd, dgnd;
  wire vtok, clk, en, rstz, se, si;
  wire [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  wire cc, tc, cv, imonen, vmonen, tmonen, so;
  wire dvdd, dgnd;
  wire [2:0] current_state;
  wire [15:0] tpreset;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200;
  wire n_201, n_202, n_203, n_204, n_205, n_206, n_207, n_208;
  wire n_209, n_210, n_211, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_234, n_235, n_236, n_237, n_238, n_239, n_240;
  wire n_242, n_243, n_244, n_245, n_246, n_247, n_248, n_323;
  assign tmonen = 1'b1;
  assign vmonen = 1'b0;
  assign imonen = 1'b0;
  assign cv = 1'b0;
  assign tc = 1'b0;
  assign cc = 1'b0;
  QDLAHEHD cc_reg(.G (n_233), .D (n_323), .Q (cc));
  QDBAHEHD cv_reg(.GB (n_236), .D (current_state[1]), .Q (cv));
  QDBAHEHD imonen_reg(.GB (n_236), .D (current_state[1]), .Q (imonen));
  QDBAHEHD tc_reg(.GB (n_229), .D (n_158), .Q (tc));
  QDBAHEHD vmonen_reg(.GB (n_234), .D (n_323), .Q (vmonen));
  AOI12CHD g6821__2398(.A1 (n_225), .B1 (n_235), .B2
       (current_state[2]), .O (n_236));
  AN3B2BHD g6822__5107(.I1 (n_239), .B1 (current_state[0]), .B2
       (current_state[1]), .O (n_235));
  OAI112BHD g6825__6260(.A1 (n_232), .B1 (n_125), .C1 (n_201), .C2
       (n_199), .O (n_239));
  NR2BHD g6826__4319(.I1 (n_228), .I2 (n_231), .O (n_234));
  OR2CHD g6827__8428(.I1 (n_231), .I2 (n_223), .O (n_233));
  AOI13BHD g6828__5526(.A1 (n_230), .B1 (n_215), .B2 (n_164), .B3
       (n_121), .O (n_232));
  OAI112BHD g6830__6783(.A1 (n_204), .B1 (n_202), .C1 (n_227), .C2
       (n_184), .O (n_230));
  OAI13BHD g6831__3680(.A1 (n_224), .B1 (n_240), .B2 (n_1), .B3
       (n_242), .O (n_231));
  NR2BHD g6832__1617(.I1 (n_228), .I2 (n_223), .O (n_229));
  AOI12CHD g6833__2802(.A1 (n_240), .B1 (n_237), .B2 (n_226), .O
       (n_228));
  AO112EHD g6834__1705(.A1 (n_248), .B1 (n_247), .C1 (n_192), .C2
       (n_147), .O (n_242));
  OR3B1EHD g6835__5122(.I1 (n_199), .I2 (n_222), .B1 (n_106), .O
       (n_227));
  OR2CHD g6836__8246(.I1 (n_246), .I2 (n_1), .O (n_226));
  INVDHD g6837(.I (n_224), .O (n_225));
  OR2B1CHD g6838__7098(.I1 (n_323), .B1 (n_247), .O (n_224));
  AN3B2BHD g6839__6131(.I1 (n_244), .B1 (n_158), .B2 (n_248), .O
       (n_223));
  OAI12CHD g6840__1881(.A1 (n_102), .B1 (n_221), .B2 (n_108), .O
       (n_246));
  OAI112BHD g6841__5115(.A1 (n_220), .B1 (n_107), .C1 (n_101), .C2
       (n_136), .O (n_248));
  OAI222BHD g6842__7482(.A1 (n_96), .A2 (n_218), .B1 (tpreset[6]), .B2
       (tmax[6]), .C1 (tmax[7]), .C2 (tpreset[7]), .O (n_222));
  OR3EHD g6843__4733(.I1 (n_243), .I2 (n_245), .I3 (current_state[2]),
       .O (n_237));
  MOAI1CHD g6844__6161(.A1 (n_65), .A2 (vpreset[7]), .B1 (n_219), .B2
       (n_147), .O (n_247));
  OAI112BHD g6845__9315(.A1 (n_217), .B1 (n_119), .C1 (n_176), .C2
       (n_159), .O (n_245));
  OAI112BHD g6846__9945(.A1 (n_214), .B1 (n_120), .C1 (n_169), .C2
       (n_156), .O (n_243));
  AOI12CHD g6847__2883(.A1 (n_116), .B1 (n_216), .B2 (n_136), .O
       (n_221));
  OAI112BHD g6848__2346(.A1 (n_102), .B1 (n_117), .C1 (n_212), .C2
       (n_137), .O (n_220));
  OAI22CHD g6849__1666(.A1 (n_133), .A2 (n_213), .B1 (n_67), .B2
       (vpreset[6]), .O (n_219));
  MAO222CHD g6850__7410(.A1 (n_211), .B1 (tpreset[5]), .C1 (tmax[5]),
       .O (n_218));
  MAOI1CHD g6851__6417(.A1 (n_209), .A2 (n_114), .B1 (tbat[6]), .B2
       (n_152), .O (n_217));
  OAI12CHD g6852__5477(.A1 (n_113), .B1 (n_208), .B2 (n_137), .O
       (n_216));
  OAI112BHD g6853__2398(.A1 (n_210), .B1 (n_140), .C1 (n_81), .C2
       (ibat[6]), .O (n_215));
  MAOI1CHD g6854__5107(.A1 (n_144), .A2 (tbat[6]), .B1 (n_156), .B2
       (n_206), .O (n_214));
  AOI22BHD g6855__6260(.A1 (n_205), .A2 (n_115), .B1 (n_72), .B2
       (vbat[5]), .O (n_213));
  AN2B1CHD g6856__4319(.I1 (n_113), .B1 (n_207), .O (n_212));
  MAO222CHD g6857__8428(.A1 (n_200), .B1 (tpreset[4]), .C1 (tmax[4]),
       .O (n_211));
  MAO222CHD g6858__5526(.A1 (n_203), .B1 (n_85), .C1 (ibat[5]), .O
       (n_210));
  AOI112BHD g6859__6783(.A1 (n_159), .B1 (n_124), .C1 (n_189), .C2
       (n_161), .O (n_209));
  AOI13BHD g6860__3680(.A1 (n_110), .B1 (n_193), .B2 (n_131), .B3
       (n_139), .O (n_208));
  AOI13BHD g6861__1617(.A1 (n_132), .B1 (n_191), .B2 (n_111), .B3
       (n_109), .O (n_207));
  OAI112BHD g6862__2802(.A1 (n_196), .B1 (n_112), .C1 (n_74), .C2
       (tbat[4]), .O (n_206));
  OAI22CHD g6863__1705(.A1 (n_134), .A2 (n_198), .B1 (n_66), .B2
       (vpreset[4]), .O (n_205));
  AOI22BHD g6864__5122(.A1 (n_194), .A2 (n_179), .B1 (n_103), .B2
       (n_104), .O (n_204));
  OAI12CHD g6865__8246(.A1 (n_195), .B1 (n_73), .B2 (iend[4]), .O
       (n_203));
  AO112EHD g6866__7098(.A1 (n_190), .B1 (n_155), .C1 (n_178), .C2
       (n_127), .O (n_202));
  AOI13BHD g6867__6131(.A1 (n_197), .B1 (n_181), .B2 (n_146), .B3
       (tpreset[8]), .O (n_201));
  MAO222CHD g6868__1881(.A1 (n_188), .B1 (tpreset[3]), .C1 (tmax[3]),
       .O (n_200));
  AOI22BHD g6869__5115(.A1 (n_186), .A2 (n_135), .B1 (n_82), .B2
       (vbat[3]), .O (n_198));
  OAI112BHD g6870__7482(.A1 (vbat[6]), .B1 (vbat[7]), .C1 (n_177), .C2
       (vbat[5]), .O (n_244));
  OR2B1CHD g6871__4733(.I1 (n_190), .B1 (n_182), .O (n_199));
  OAI22CHD g6872__6161(.A1 (n_171), .A2 (n_184), .B1 (n_157), .B2
       (n_128), .O (n_197));
  MAO222CHD g6873__9315(.A1 (n_185), .B1 (n_87), .C1 (tbat[3]), .O
       (n_196));
  AO222CHD g6874__9945(.A1 (n_173), .A2 (n_143), .B1 (n_70), .B2
       (iend[3]), .C1 (n_73), .C2 (iend[4]), .O (n_195));
  OAI22CHD g6875__2883(.A1 (n_99), .A2 (n_187), .B1 (n_148), .B2
       (n_105), .O (n_194));
  ND2CHD g6876__2346(.I1 (n_183), .I2 (n_109), .O (n_193));
  AN4B1BHD g6877__1666(.I1 (n_166), .I2 (n_135), .I3 (n_115), .B1
       (n_134), .O (n_192));
  OAI112BHD g6878__7410(.A1 (n_139), .B1 (n_118), .C1 (n_167), .C2
       (n_145), .O (n_191));
  AOI22BHD g6879__6417(.A1 (n_172), .A2 (n_138), .B1 (n_69), .B2
       (tempmin[3]), .O (n_189));
  MAO222CHD g6880__5477(.A1 (n_175), .B1 (tpreset[2]), .C1 (tmax[2]),
       .O (n_188));
  OAI112BHD g6881__2398(.A1 (n_180), .B1 (n_179), .C1 (n_149), .C2
       (n_168), .O (n_190));
  ND2DHD g6882__5107(.I1 (n_180), .I2 (n_149), .O (n_187));
  OAI12CHD g6883__6260(.A1 (n_170), .B1 (n_75), .B2 (vpreset[2]), .O
       (n_186));
  OAI12CHD g6884__4319(.A1 (n_174), .B1 (n_78), .B2 (tempmax[2]), .O
       (n_185));
  OAI22CHD g6885__8428(.A1 (vbat[0]), .A2 (n_165), .B1 (n_142), .B2
       (n_92), .O (n_183));
  AOI22BHD g6886__5526(.A1 (n_154), .A2 (n_126), .B1 (n_155), .B2
       (n_127), .O (n_182));
  OAI12CHD g6887__6783(.A1 (n_181), .B1 (n_146), .B2 (tpreset[8]), .O
       (n_184));
  OR2EHD g6888__3680(.I1 (n_126), .I2 (n_154), .O (n_178));
  NR2BHD g6889__1617(.I1 (n_66), .I2 (n_160), .O (n_177));
  OA22CHD g6890__2802(.A1 (tbat[4]), .A2 (n_153), .B1 (n_89), .B2
       (tbat[5]), .O (n_176));
  ND2CHD g6891__1705(.I1 (n_157), .I2 (n_128), .O (n_181));
  ND2CHD g6892__5122(.I1 (n_148), .I2 (n_105), .O (n_180));
  OR2EHD g6893__8246(.I1 (n_104), .I2 (n_103), .O (n_179));
  MAO222CHD g6894__7098(.A1 (n_91), .B1 (tpreset[1]), .C1 (tmax[1]), .O
       (n_175));
  OAI222BHD g6895__6131(.A1 (tbat[1]), .A2 (n_86), .B1 (n_151), .B2
       (tbat[0]), .C1 (tbat[2]), .C2 (n_71), .O (n_174));
  OAI112BHD g6896__1881(.A1 (n_162), .B1 (n_123), .C1 (n_84), .C2
       (ibat[1]), .O (n_173));
  OA112CHD g6897__5115(.A1 (n_163), .B1 (n_94), .C1 (n_78), .C2
       (tempmin[2]), .O (n_172));
  AOI13BHD g6898__7482(.A1 (n_98), .B1 (n_106), .B2 (tpreset[7]), .B3
       (tmax[7]), .O (n_171));
  OAI112BHD g6899__4733(.A1 (n_150), .B1 (n_141), .C1 (vbat[1]), .C2
       (vbat[0]), .O (n_170));
  AOI13BHD g6900__6161(.A1 (n_97), .B1 (n_112), .B2 (n_74), .B3
       (tbat[4]), .O (n_169));
  INVDHD g6901(.I (n_99), .O (n_168));
  AOI12CHD g6902__9315(.A1 (vcutoff[0]), .B1 (n_95), .B2 (n_100), .O
       (n_167));
  AOI112BHD g6903__9945(.A1 (n_133), .B1 (n_93), .C1 (n_62), .C2
       (vpreset[1]), .O (n_166));
  OR2B1CHD g6904__2883(.I1 (n_145), .B1 (vcutoff[0]), .O (n_165));
  ND3CHD g6905__2346(.I1 (n_140), .I2 (n_81), .I3 (ibat[6]), .O
       (n_164));
  OR3B2CHD g6906__1666(.I1 (tempmin[0]), .B1 (n_122), .B2 (tbat[0]), .O
       (n_163));
  AO112EHD g6907__7410(.A1 (n_90), .B1 (ibat[0]), .C1 (n_84), .C2
       (ibat[1]), .O (n_162));
  ND3CHD g6908__6417(.I1 (n_138), .I2 (n_78), .I3 (tempmin[2]), .O
       (n_161));
  OA12CHD g6909__5477(.A1 (n_64), .B1 (n_100), .B2 (n_75), .O (n_160));
  ND2CHD g6910__2398(.I1 (n_114), .I2 (tempmin[4]), .O (n_153));
  ND2CHD g6911__5107(.I1 (n_130), .I2 (tempmin[6]), .O (n_152));
  OAI12CHD g6912__6260(.A1 (tempmax[0]), .B1 (n_68), .B2 (tempmax[1]),
       .O (n_151));
  ND2CHD g6913__4319(.I1 (n_100), .I2 (vpreset[1]), .O (n_150));
  OAI12CHD g6914__8428(.A1 (n_130), .B1 (n_77), .B2 (tempmin[6]), .O
       (n_159));
  OR2B1CHD g6915__5526(.I1 (n_238), .B1 (current_state[1]), .O (n_158));
  OAI12CHD g6916__6783(.A1 (n_126), .B1 (tpreset[10]), .B2 (n_80), .O
       (n_157));
  OAI12CHD g6917__3680(.A1 (n_129), .B1 (n_88), .B2 (tbat[6]), .O
       (n_156));
  OAI12CHD g6918__1617(.A1 (n_99), .B1 (tpreset[12]), .B2 (n_79), .O
       (n_155));
  OAI12CHD g6919__2802(.A1 (n_127), .B1 (tpreset[11]), .B2 (n_76), .O
       (n_154));
  AN2CHD g6920__1705(.I1 (n_129), .I2 (n_88), .O (n_144));
  OA22CHD g6921__5122(.A1 (iend[2]), .A2 (n_83), .B1 (n_70), .B2
       (iend[3]), .O (n_143));
  AOI22BHD g6922__8246(.A1 (n_62), .A2 (vcutoff[1]), .B1 (n_75), .B2
       (vcutoff[2]), .O (n_142));
  OAI12CHD g6923__7098(.A1 (vpreset[0]), .B1 (n_62), .B2 (vpreset[1]),
       .O (n_141));
  MOAI1CHD g6924__6131(.A1 (tpreset[13]), .A2 (tmax[5]), .B1
       (tpreset[13]), .B2 (tmax[5]), .O (n_149));
  MAOI1CHD g6925__1881(.A1 (tpreset[14]), .A2 (tmax[6]), .B1 (tmax[6]),
       .B2 (tpreset[14]), .O (n_148));
  AOI22BHD g6926__5115(.A1 (n_67), .A2 (vpreset[6]), .B1 (n_65), .B2
       (vpreset[7]), .O (n_147));
  MOAI1CHD g6927__7482(.A1 (tpreset[9]), .A2 (tmax[1]), .B1
       (tpreset[9]), .B2 (tmax[1]), .O (n_146));
  OAI22CHD g6928__4733(.A1 (vcutoff[1]), .A2 (n_62), .B1 (n_75), .B2
       (vcutoff[2]), .O (n_145));
  ND3CHD g6929__6161(.I1 (n_1), .I2 (current_state[1]), .I3
       (current_state[0]), .O (n_323));
  INVDHD g6930(.I (n_131), .O (n_132));
  OR2B1CHD g6931__9315(.I1 (tmax[7]), .B1 (so), .O (n_125));
  AN2B1CHD g6932__9945(.I1 (tbat[4]), .B1 (tempmin[4]), .O (n_124));
  ND2CHD g6933__2883(.I1 (n_83), .I2 (iend[2]), .O (n_123));
  ND2CHD g6934__2346(.I1 (n_68), .I2 (tempmin[1]), .O (n_122));
  OR2B1CHD g6935__1666(.I1 (iend[7]), .B1 (ibat[7]), .O (n_121));
  OR2B1CHD g6936__7410(.I1 (tempmax[7]), .B1 (tbat[7]), .O (n_120));
  OR2B1CHD g6937__6417(.I1 (tbat[7]), .B1 (tempmin[7]), .O (n_119));
  ND2CHD g6938__5477(.I1 (n_75), .I2 (vcutoff[2]), .O (n_118));
  OR2B1CHD g6939__2398(.I1 (ibat[7]), .B1 (iend[7]), .O (n_140));
  ND2CHD g6940__5107(.I1 (n_64), .I2 (vcutoff[3]), .O (n_139));
  OR2CHD g6941__6260(.I1 (tempmin[3]), .I2 (n_69), .O (n_138));
  AN2B1CHD g6942__4319(.I1 (vcutoff[5]), .B1 (vbat[5]), .O (n_137));
  ND2CHD g6943__8428(.I1 (n_67), .I2 (vcutoff[6]), .O (n_136));
  ND2CHD g6944__5526(.I1 (n_75), .I2 (vpreset[2]), .O (n_135));
  NR2BHD g6945__6783(.I1 (vbat[3]), .I2 (n_82), .O (n_134));
  NR2BHD g6946__3680(.I1 (vbat[5]), .I2 (n_72), .O (n_133));
  ND2CHD g6947__1617(.I1 (n_66), .I2 (vcutoff[4]), .O (n_131));
  OR2B1CHD g6948__2802(.I1 (tempmin[7]), .B1 (tbat[7]), .O (n_130));
  OR2B1CHD g6949__1705(.I1 (tbat[7]), .B1 (tempmax[7]), .O (n_129));
  OR2B1CHD g6950__5122(.I1 (tmax[1]), .B1 (tpreset[9]), .O (n_128));
  ND2CHD g6951__8246(.I1 (tpreset[11]), .I2 (n_76), .O (n_127));
  ND2DHD g6952__7098(.I1 (tpreset[10]), .I2 (n_80), .O (n_126));
  OR2B1CHD g6953__6131(.I1 (current_state[1]), .B1 (current_state[0]),
       .O (n_240));
  INVDHD g6954(.I (n_116), .O (n_117));
  INVDHD g6955(.I (n_110), .O (n_111));
  INVDHD g6956(.I (n_107), .O (n_108));
  INVDHD g6957(.I (n_101), .O (n_102));
  NR2CHD g6958__1881(.I1 (tmax[0]), .I2 (tpreset[8]), .O (n_98));
  AN2B1CHD g6959__5115(.I1 (tbat[5]), .B1 (tempmax[5]), .O (n_97));
  AN2EHD g6960__7482(.I1 (tpreset[6]), .I2 (tmax[6]), .O (n_96));
  OR2B1CHD g6961__4733(.I1 (vcutoff[1]), .B1 (vbat[0]), .O (n_95));
  OR2CHD g6962__6161(.I1 (tempmin[1]), .I2 (n_68), .O (n_94));
  AN2B1CHD g6963__9315(.I1 (vpreset[0]), .B1 (vbat[0]), .O (n_93));
  NR2BHD g6964__9945(.I1 (vcutoff[6]), .I2 (n_67), .O (n_116));
  ND2CHD g6965__2883(.I1 (n_66), .I2 (vpreset[4]), .O (n_115));
  ND2CHD g6966__2346(.I1 (n_89), .I2 (tbat[5]), .O (n_114));
  OR2B1CHD g6967__1666(.I1 (vcutoff[5]), .B1 (vbat[5]), .O (n_113));
  OR2B1CHD g6968__7410(.I1 (tbat[5]), .B1 (tempmax[5]), .O (n_112));
  NR2BHD g6969__6417(.I1 (vcutoff[4]), .I2 (n_66), .O (n_110));
  OR2CHD g6970__5477(.I1 (vcutoff[3]), .I2 (n_64), .O (n_109));
  ND2CHD g6971__2398(.I1 (n_65), .I2 (vcutoff[7]), .O (n_107));
  NR2BHD g6972__5107(.I1 (vcutoff[2]), .I2 (n_75), .O (n_92));
  ND2CHD g6973__6260(.I1 (tpreset[8]), .I2 (tmax[0]), .O (n_106));
  OR2B1CHD g6974__4319(.I1 (tmax[5]), .B1 (tpreset[13]), .O (n_105));
  AN2EHD g6975__8428(.I1 (tpreset[0]), .I2 (tmax[0]), .O (n_91));
  OR2EHD g6976__5526(.I1 (current_state[0]), .I2 (current_state[2]), .O
       (n_238));
  OR2B1CHD g6977__6783(.I1 (so), .B1 (tmax[7]), .O (n_104));
  AN2B1CHD g6978__3680(.I1 (tpreset[14]), .B1 (tmax[6]), .O (n_103));
  NR2BHD g6979__1617(.I1 (vcutoff[7]), .I2 (n_65), .O (n_101));
  ND2CHD g6980__2802(.I1 (vbat[1]), .I2 (vbat[0]), .O (n_100));
  ND2DHD g6981__1705(.I1 (tpreset[12]), .I2 (n_79), .O (n_99));
  INVDHD g6982(.I (iend[0]), .O (n_90));
  INVDHD g6983(.I (tempmin[5]), .O (n_89));
  INVDHD g6984(.I (tempmax[6]), .O (n_88));
  INVDHD g6985(.I (tempmax[3]), .O (n_87));
  INVDHD g6986(.I (tempmax[1]), .O (n_86));
  INVDHD g6987(.I (iend[5]), .O (n_85));
  INVDHD g6988(.I (iend[1]), .O (n_84));
  INVDHD g6989(.I (ibat[2]), .O (n_83));
  INVDHD g6990(.I (vpreset[3]), .O (n_82));
  INVDHD g6991(.I (iend[6]), .O (n_81));
  INVDHD g6992(.I (tmax[2]), .O (n_80));
  INVDHD g6993(.I (tmax[4]), .O (n_79));
  INVDHD g6994(.I (tbat[2]), .O (n_78));
  INVDHD g6995(.I (tbat[6]), .O (n_77));
  INVDHD g6996(.I (tmax[3]), .O (n_76));
  INVDHD g6997(.I (vbat[2]), .O (n_75));
  INVDHD g6998(.I (tempmax[4]), .O (n_74));
  INVDHD g6999(.I (ibat[4]), .O (n_73));
  INVDHD g7000(.I (vpreset[5]), .O (n_72));
  INVDHD g7001(.I (tempmax[2]), .O (n_71));
  INVDHD g7002(.I (ibat[3]), .O (n_70));
  INVDHD g7003(.I (tbat[3]), .O (n_69));
  INVDHD g7004(.I (tbat[1]), .O (n_68));
  INVDHD g7005(.I (vbat[6]), .O (n_67));
  INVDHD g7006(.I (vbat[4]), .O (n_66));
  INVDHD g7007(.I (vbat[7]), .O (n_65));
  INVDHD g7008(.I (vbat[3]), .O (n_64));
  INVDHD g7010(.I (vbat[1]), .O (n_62));
  QDFZRBEHD \current_state_reg[0] (.RB (rstz), .CK (clk), .D (n_36),
       .TD (si), .SEL (se), .Q (current_state[0]));
  QDFZRBEHD \current_state_reg[1] (.RB (rstz), .CK (clk), .D (n_32),
       .TD (current_state[0]), .SEL (se), .Q (current_state[1]));
  QDFZRBEHD \current_state_reg[2] (.RB (rstz), .CK (clk), .D (n_31),
       .TD (current_state[1]), .SEL (se), .Q (current_state[2]));
  QDFZRBEHD \tpreset_reg[0] (.RB (rstz), .CK (clk), .D (n_27), .TD
       (current_state[2]), .SEL (se), .Q (tpreset[0]));
  QDFZRBEHD \tpreset_reg[1] (.RB (rstz), .CK (clk), .D (n_25), .TD
       (tpreset[0]), .SEL (se), .Q (tpreset[1]));
  QDFZRBEHD \tpreset_reg[2] (.RB (rstz), .CK (clk), .D (n_34), .TD
       (tpreset[1]), .SEL (se), .Q (tpreset[2]));
  QDFZRBEHD \tpreset_reg[3] (.RB (rstz), .CK (clk), .D (n_37), .TD
       (tpreset[2]), .SEL (se), .Q (tpreset[3]));
  QDFZRBEHD \tpreset_reg[4] (.RB (rstz), .CK (clk), .D (n_39), .TD
       (tpreset[3]), .SEL (se), .Q (tpreset[4]));
  QDFZRBEHD \tpreset_reg[5] (.RB (rstz), .CK (clk), .D (n_41), .TD
       (tpreset[4]), .SEL (se), .Q (tpreset[5]));
  QDFZRBEHD \tpreset_reg[6] (.RB (rstz), .CK (clk), .D (n_43), .TD
       (tpreset[5]), .SEL (se), .Q (tpreset[6]));
  QDFZRBEHD \tpreset_reg[7] (.RB (rstz), .CK (clk), .D (n_45), .TD
       (tpreset[6]), .SEL (se), .Q (tpreset[7]));
  QDFZRBEHD \tpreset_reg[8] (.RB (rstz), .CK (clk), .D (n_47), .TD
       (tpreset[7]), .SEL (se), .Q (tpreset[8]));
  QDFZRBEHD \tpreset_reg[9] (.RB (rstz), .CK (clk), .D (n_49), .TD
       (tpreset[8]), .SEL (se), .Q (tpreset[9]));
  QDFZRBEHD \tpreset_reg[10] (.RB (rstz), .CK (clk), .D (n_51), .TD
       (tpreset[9]), .SEL (se), .Q (tpreset[10]));
  QDFZRBEHD \tpreset_reg[11] (.RB (rstz), .CK (clk), .D (n_53), .TD
       (tpreset[10]), .SEL (se), .Q (tpreset[11]));
  QDFZRBEHD \tpreset_reg[12] (.RB (rstz), .CK (clk), .D (n_55), .TD
       (tpreset[11]), .SEL (se), .Q (tpreset[12]));
  QDFZRBEHD \tpreset_reg[13] (.RB (rstz), .CK (clk), .D (n_57), .TD
       (tpreset[12]), .SEL (se), .Q (tpreset[13]));
  QDFZRBEHD \tpreset_reg[14] (.RB (rstz), .CK (clk), .D (n_59), .TD
       (tpreset[13]), .SEL (se), .Q (tpreset[14]));
  QDFZRBEHD \tpreset_reg[15] (.RB (rstz), .CK (clk), .D (n_61), .TD
       (tpreset[14]), .SEL (se), .Q (so));
  NR2BHD g4511__5122(.I1 (n_21), .I2 (n_60), .O (n_61));
  MAOI1CHD g4513__8246(.A1 (n_58), .A2 (so), .B1 (so), .B2 (n_58), .O
       (n_60));
  OA112EHD g4514__7098(.A1 (n_58), .B1 (n_22), .C1 (n_56), .C2
       (tpreset[14]), .O (n_59));
  ND2CHD g4516__6131(.I1 (n_56), .I2 (tpreset[14]), .O (n_58));
  AOI112BHD g4517__1881(.A1 (n_56), .B1 (n_21), .C1 (n_54), .C2 (n_4),
       .O (n_57));
  NR2CHD g4519__5115(.I1 (n_4), .I2 (n_54), .O (n_56));
  OA112EHD g4520__7482(.A1 (n_54), .B1 (n_22), .C1 (n_52), .C2
       (tpreset[12]), .O (n_55));
  ND2CHD g4522__4733(.I1 (n_52), .I2 (tpreset[12]), .O (n_54));
  AOI112BHD g4523__6161(.A1 (n_52), .B1 (n_21), .C1 (n_50), .C2 (n_6),
       .O (n_53));
  NR2CHD g4525__9315(.I1 (n_6), .I2 (n_50), .O (n_52));
  OA112EHD g4526__9945(.A1 (n_50), .B1 (n_22), .C1 (n_48), .C2
       (tpreset[10]), .O (n_51));
  ND2CHD g4528__2883(.I1 (n_48), .I2 (tpreset[10]), .O (n_50));
  AOI112BHD g4529__2346(.A1 (n_48), .B1 (n_21), .C1 (n_46), .C2 (n_5),
       .O (n_49));
  NR2CHD g4531__1666(.I1 (n_5), .I2 (n_46), .O (n_48));
  OA112EHD g4532__7410(.A1 (n_46), .B1 (n_22), .C1 (n_44), .C2
       (tpreset[8]), .O (n_47));
  ND2CHD g4534__6417(.I1 (n_44), .I2 (tpreset[8]), .O (n_46));
  AOI112BHD g4535__5477(.A1 (n_44), .B1 (n_21), .C1 (n_42), .C2 (n_3),
       .O (n_45));
  NR2CHD g4537__2398(.I1 (n_3), .I2 (n_42), .O (n_44));
  OA112EHD g4538__5107(.A1 (n_42), .B1 (n_22), .C1 (n_40), .C2
       (tpreset[6]), .O (n_43));
  ND2CHD g4540__6260(.I1 (n_40), .I2 (tpreset[6]), .O (n_42));
  AOI112BHD g4541__4319(.A1 (n_40), .B1 (n_21), .C1 (n_38), .C2 (n_8),
       .O (n_41));
  NR2CHD g4543__8428(.I1 (n_8), .I2 (n_38), .O (n_40));
  OA112EHD g4544__5526(.A1 (n_38), .B1 (n_22), .C1 (n_35), .C2
       (tpreset[4]), .O (n_39));
  ND2CHD g4546__6783(.I1 (n_35), .I2 (tpreset[4]), .O (n_38));
  AOI112BHD g4547__3680(.A1 (n_21), .B1 (n_35), .C1 (n_28), .C2 (n_7),
       .O (n_37));
  OAI112BHD g4550__1617(.A1 (n_33), .B1 (n_20), .C1 (n_240), .C2
       (n_30), .O (n_36));
  OA112EHD g4553__2802(.A1 (n_22), .B1 (n_28), .C1 (n_11), .C2
       (tpreset[2]), .O (n_34));
  MAOI1CHD g4554__1705(.A1 (n_15), .A2 (n_29), .B1 (n_14), .B2 (n_238),
       .O (n_33));
  NR2CHD g4555__5122(.I1 (n_7), .I2 (n_28), .O (n_35));
  AOI112BHD g4556__8246(.A1 (n_19), .B1 (n_10), .C1 (n_23), .C2
       (n_237), .O (n_32));
  MOAI1CHD g4557__7098(.A1 (current_state[1]), .A2 (n_18), .B1 (n_15),
       .B2 (n_26), .O (n_31));
  AOI222BHD g4560__6131(.A1 (n_17), .A2 (n_246), .B1 (n_16), .B2
       (n_245), .C1 (n_1), .C2 (n_243), .O (n_30));
  MOAI1CHD g4561__1881(.A1 (current_state[0]), .A2 (n_24), .B1 (n_17),
       .B2 (n_10), .O (n_29));
  NR2BHD g4562__5115(.I1 (tpreset[0]), .I2 (n_21), .O (n_27));
  ND2CHD g4563__7482(.I1 (n_11), .I2 (tpreset[2]), .O (n_28));
  AO12CHD g4564__4733(.A1 (n_10), .B1 (n_16), .B2 (n_13), .O (n_26));
  NR3BHD g4565__6161(.I1 (n_9), .I2 (n_11), .I3 (n_21), .O (n_25));
  ND2DHD g4566__9315(.I1 (n_16), .I2 (n_239), .O (n_24));
  ND2CHD g4567__9945(.I1 (n_15), .I2 (n_18), .O (n_23));
  INVDHD g4568(.I (n_22), .O (n_21));
  OR3B2CHD g4569__2883(.I1 (n_13), .B1 (n_1), .B2 (current_state[1]),
       .O (n_20));
  OA112EHD g4570__2346(.A1 (n_240), .B1 (n_13), .C1 (n_0), .C2
       (current_state[0]), .O (n_19));
  AN2EHD g4571__1666(.I1 (n_12), .I2 (n_15), .O (n_22));
  INVDHD g4572(.I (n_17), .O (n_16));
  ND3CHD g4573__7410(.I1 (current_state[2]), .I2 (n_242), .I3 (n_246),
       .O (n_18));
  OAI12CHD g4574__6417(.A1 (n_238), .B1 (n_2), .B2 (n_1), .O (n_17));
  MAOI1CHD g4575__5477(.A1 (n_0), .A2 (en), .B1 (n_248), .B2 (n_0), .O
       (n_14));
  AOI22BHD g4576__2398(.A1 (n_1), .A2 (n_0), .B1 (current_state[2]),
       .B2 (current_state[1]), .O (n_15));
  ND2DHD g4577__5107(.I1 (n_323), .I2 (current_state[0]), .O (n_12));
  OR2B1CHD g4578__6260(.I1 (n_247), .B1 (current_state[0]), .O (n_13));
  NR2CHD g4579__4319(.I1 (tpreset[1]), .I2 (tpreset[0]), .O (n_9));
  AN2EHD g4580__8428(.I1 (tpreset[1]), .I2 (tpreset[0]), .O (n_11));
  NR2CHD g4581__5526(.I1 (n_244), .I2 (current_state[0]), .O (n_10));
  INVDHD g4582(.I (tpreset[5]), .O (n_8));
  INVDHD g4586(.I (tpreset[3]), .O (n_7));
  INVDHD g4593(.I (tpreset[11]), .O (n_6));
  INVDHD g4609(.I (tpreset[9]), .O (n_5));
  INVDHD g4613(.I (tpreset[13]), .O (n_4));
  INVDHD g4614(.I (tpreset[7]), .O (n_3));
  INVDHD g4622(.I (current_state[0]), .O (n_2));
  INVDHD g4627(.I (current_state[2]), .O (n_1));
  INVDHD g4635(.I (current_state[1]), .O (n_0));
endmodule

