
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Dec  6 2024 12:43:19 WET (Dec  6 2024 12:43:19 UTC)

// Verification Directory fv/BATCHARGER_controller 

module BATCHARGER_controller(cc, tc, cv, imonen, vmonen, tmonen, vtok,
     vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax, tmax, iend,
     clk, en, rstz, dvdd, dgnd, si, se, so);
  input vtok, clk, en, rstz, si, se;
  input [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  output cc, tc, cv, imonen, vmonen, tmonen, so;
  inout dvdd, dgnd;
  wire vtok, clk, en, rstz, si, se;
  wire [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  wire cc, tc, cv, imonen, vmonen, tmonen, so;
  wire dvdd, dgnd;
  wire [2:0] current_state;
  wire [15:0] tpreset;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200;
  wire n_201, n_202, n_203, n_204, n_205, n_206, n_207, n_208;
  wire n_209, n_210, n_211, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_234, n_235, n_236, n_237, n_238, n_314, n_315;
  wire n_316, n_317, n_318, n_319, n_1651_BAR;
  assign tmonen = 1'b1;
  assign vmonen = 1'b0;
  assign imonen = 1'b0;
  assign cv = 1'b0;
  assign tc = 1'b0;
  assign cc = 1'b0;
  INVCKDHD g4865(.I (n_319), .O (n_231));
  QDLAHEHD cc_reg(.G (n_225), .D (n_316), .Q (cc));
  QDLAHEHD cv_reg(.G (n_230), .D (n_150), .Q (cv));
  QDLAHEHD imonen_reg(.G (n_230), .D (n_150), .Q (imonen));
  QDLAHEHD tc_reg(.G (n_220), .D (n_314), .Q (tc));
  QDBAHEHD vmonen_reg(.GB (n_224), .D (n_316), .Q (vmonen));
  OAI13BHD g7969__2398(.A1 (n_217), .B1 (n_229), .B2 (n_233), .B3
       (current_state[0]), .O (n_230));
  INVDHD g7970(.I (n_318), .O (n_229));
  OAI112BHD g7971__5107(.A1 (n_228), .B1 (n_98), .C1 (n_198), .C2
       (n_193), .O (n_318));
  AOI112BHD g7972__6260(.A1 (n_216), .B1 (n_226), .C1 (n_227), .C2
       (iend[7]), .O (n_228));
  ND2CHD g7975__4319(.I1 (n_221), .I2 (ibat[7]), .O (n_227));
  NR2BHD g7976__8428(.I1 (ibat[7]), .I2 (n_221), .O (n_226));
  ND2CHD g7977__5526(.I1 (n_223), .I2 (n_219), .O (n_225));
  NR2BHD g7978__6783(.I1 (n_235), .I2 (n_222), .O (n_224));
  INVDHD g7980(.I (n_222), .O (n_223));
  OAI12CHD g7981__3680(.A1 (n_217), .B1 (n_315), .B2 (n_317), .O
       (n_222));
  MAO222CHD g7982__1617(.A1 (n_218), .B1 (n_92), .C1 (ibat[6]), .O
       (n_221));
  OR2B1CHD g7983__2802(.I1 (n_235), .B1 (n_219), .O (n_220));
  OR3B2CHD g7984__1705(.I1 (n_238), .B1 (n_236), .B2 (n_192), .O
       (n_317));
  OAI22CHD g7985__5122(.A1 (n_319), .A2 (n_232), .B1 (n_315), .B2
       (n_234), .O (n_235));
  OR3B1CHD g7986__8246(.I1 (n_238), .I2 (n_314), .B1 (n_237), .O
       (n_219));
  MAO222CHD g7987__7098(.A1 (n_211), .B1 (n_94), .C1 (ibat[5]), .O
       (n_218));
  OR2CHD g7988__6131(.I1 (n_236), .I2 (n_316), .O (n_217));
  OAI112BHD g7989__1881(.A1 (n_215), .B1 (n_161), .C1 (n_171), .C2
       (n_152), .O (n_319));
  OAI112BHD g7990__5115(.A1 (n_214), .B1 (n_189), .C1 (n_125), .C2
       (n_117), .O (n_216));
  AO12CHD g7991__7482(.A1 (n_110), .B1 (n_212), .B2 (n_123), .O
       (n_234));
  OAI12CHD g7992__4733(.A1 (n_123), .B1 (n_213), .B2 (n_110), .O
       (n_238));
  OAI112BHD g7993__6161(.A1 (n_210), .B1 (n_130), .C1 (n_109), .C2
       (n_124), .O (n_236));
  NR3BHD g7994__9315(.I1 (n_179), .I2 (n_208), .I3 (n_207), .O (n_215));
  MAOI1CHD g7995__9945(.A1 (n_175), .A2 (n_176), .B1 (n_193), .B2
       (n_209), .O (n_214));
  AOI12CHD g7996__2883(.A1 (n_121), .B1 (n_206), .B2 (n_106), .O
       (n_213));
  OAI12CHD g7997__2346(.A1 (n_106), .B1 (n_205), .B2 (n_121), .O
       (n_212));
  MAO222CHD g7998__1666(.A1 (n_201), .B1 (n_89), .C1 (ibat[4]), .O
       (n_211));
  OR2B1CHD g7999__7410(.I1 (n_109), .B1 (n_204), .O (n_210));
  OAI112BHD g8000__6417(.A1 (n_202), .B1 (n_186), .C1 (tpreset[7]), .C2
       (tmax[7]), .O (n_209));
  OAI22CHD g8001__5477(.A1 (n_151), .A2 (n_203), .B1 (n_85), .B2
       (tempmax[7]), .O (n_208));
  OAI13BHD g8002__2398(.A1 (n_116), .B1 (n_197), .B2 (n_152), .B3
       (n_113), .O (n_207));
  OAI12CHD g8003__5107(.A1 (n_120), .B1 (n_199), .B2 (n_104), .O
       (n_206));
  AOI12CHD g8004__6260(.A1 (n_104), .B1 (n_200), .B2 (n_120), .O
       (n_205));
  AOI13BHD g8005__4319(.A1 (n_137), .B1 (n_195), .B2 (n_103), .B3
       (n_127), .O (n_204));
  OAI112BHD g8006__8428(.A1 (n_196), .B1 (n_132), .C1 (n_91), .C2
       (tbat[3]), .O (n_203));
  OAI222BHD g8007__5526(.A1 (n_158), .A2 (n_191), .B1 (n_156), .B2
       (n_136), .C1 (n_133), .C2 (n_158), .O (n_202));
  MAO222CHD g8008__6783(.A1 (n_188), .B1 (n_93), .C1 (ibat[3]), .O
       (n_201));
  OAI12CHD g8009__3680(.A1 (n_105), .B1 (n_190), .B2 (n_126), .O
       (n_200));
  AOI13BHD g8010__1617(.A1 (n_126), .B1 (n_184), .B2 (n_105), .B3
       (n_108), .O (n_199));
  AOI13BHD g8011__2802(.A1 (n_194), .B1 (n_173), .B2 (n_140), .B3
       (tpreset[8]), .O (n_198));
  OAI222BHD g8012__1705(.A1 (tempmin[3]), .A2 (n_67), .B1 (n_181), .B2
       (n_100), .C1 (tempmin[4]), .C2 (n_69), .O (n_197));
  AOI22BHD g8013__5122(.A1 (n_182), .A2 (n_99), .B1 (n_69), .B2
       (tempmax[4]), .O (n_196));
  OAI112BHD g8014__8246(.A1 (n_180), .B1 (n_162), .C1 (n_81), .C2
       (vpreset[4]), .O (n_195));
  OAI22CHD g8015__7098(.A1 (n_134), .A2 (n_185), .B1 (n_153), .B2
       (n_122), .O (n_194));
  ND2CHD g8016__6131(.I1 (n_183), .I2 (n_112), .O (n_192));
  OAI222BHD g8017__1881(.A1 (n_95), .A2 (n_169), .B1 (tpreset[2]), .B2
       (tmax[2]), .C1 (tmax[3]), .C2 (tpreset[3]), .O (n_191));
  ND2DHD g8018__5115(.I1 (n_187), .I2 (n_174), .O (n_193));
  AOI112BHD g8019__7482(.A1 (n_178), .B1 (n_107), .C1 (n_168), .C2
       (vbat[0]), .O (n_190));
  OR3B2CHD g8020__4733(.I1 (n_143), .B1 (n_187), .B2 (n_177), .O
       (n_189));
  MAO222CHD g8021__6161(.A1 (n_163), .B1 (n_76), .C1 (ibat[2]), .O
       (n_188));
  OAI112BHD g8022__9315(.A1 (vbat[6]), .B1 (vbat[7]), .C1 (n_170), .C2
       (vbat[5]), .O (n_237));
  INVDHD g8023(.I (n_185), .O (n_186));
  OAI12CHD g8024__9945(.A1 (n_178), .B1 (n_144), .B2 (vbat[0]), .O
       (n_184));
  AN4B1BHD g8025__2883(.I1 (n_138), .I2 (n_127), .I3 (n_130), .B1
       (n_154), .O (n_183));
  AN2EHD g8026__2346(.I1 (n_176), .I2 (n_172), .O (n_187));
  OAI112BHD g8027__1666(.A1 (n_173), .B1 (n_96), .C1 (n_140), .C2
       (tpreset[8]), .O (n_185));
  MAO222CHD g8028__7410(.A1 (n_165), .B1 (n_68), .C1 (tempmax[2]), .O
       (n_182));
  MAO222CHD g8029__6417(.A1 (n_166), .B1 (n_68), .C1 (tempmin[2]), .O
       (n_181));
  AOI22BHD g8030__5477(.A1 (n_164), .A2 (n_138), .B1 (n_73), .B2
       (vbat[3]), .O (n_180));
  OAI22CHD g8031__2398(.A1 (n_151), .A2 (n_167), .B1 (n_149), .B2
       (tbat[6]), .O (n_179));
  OAI12CHD g8032__5107(.A1 (n_119), .B1 (n_142), .B2 (n_101), .O
       (n_177));
  AN2CHD g8033__6260(.I1 (n_168), .I2 (n_160), .O (n_178));
  OAI22CHD g8034__4319(.A1 (n_118), .A2 (n_141), .B1 (n_139), .B2
       (n_102), .O (n_175));
  AOI22BHD g8035__8428(.A1 (n_142), .A2 (n_101), .B1 (n_143), .B2
       (n_119), .O (n_174));
  AOI22BHD g8036__5526(.A1 (n_139), .A2 (n_102), .B1 (n_125), .B2
       (n_117), .O (n_176));
  ND2CHD g8037__6783(.I1 (n_141), .I2 (n_118), .O (n_172));
  AOI22BHD g8038__3680(.A1 (n_148), .A2 (n_69), .B1 (n_66), .B2
       (tempmin[5]), .O (n_171));
  NR2BHD g8039__1617(.I1 (n_81), .I2 (n_155), .O (n_170));
  ND2CHD g8040__2802(.I1 (n_157), .I2 (n_97), .O (n_169));
  ND2CHD g8041__1705(.I1 (n_153), .I2 (n_122), .O (n_173));
  OA22CHD g8042__5122(.A1 (n_69), .A2 (n_145), .B1 (n_66), .B2
       (tempmax[5]), .O (n_167));
  AOI22BHD g8043__8246(.A1 (n_135), .A2 (tbat[0]), .B1 (n_88), .B2
       (tbat[1]), .O (n_166));
  OAI22CHD g8044__7098(.A1 (tbat[0]), .A2 (n_146), .B1 (n_90), .B2
       (tbat[1]), .O (n_165));
  OAI12CHD g8045__6131(.A1 (n_159), .B1 (n_78), .B2 (vpreset[1]), .O
       (n_164));
  MAO222CHD g8046__1881(.A1 (n_115), .B1 (n_75), .C1 (ibat[1]), .O
       (n_163));
  AOI222BHD g8047__5115(.A1 (n_82), .A2 (vcutoff[2]), .B1 (n_147), .B2
       (n_78), .C1 (n_65), .C2 (vcutoff[3]), .O (n_168));
  OR3B2CHD g8048__7482(.I1 (vpreset[2]), .B1 (n_114), .B2 (vbat[2]), .O
       (n_162));
  OR3B2CHD g8049__4733(.I1 (tempmax[6]), .B1 (n_129), .B2 (tbat[6]), .O
       (n_161));
  OR2B1CHD g8050__6161(.I1 (n_144), .B1 (vcutoff[0]), .O (n_160));
  OR3B2CHD g8051__9315(.I1 (vpreset[0]), .B1 (n_112), .B2 (vbat[0]), .O
       (n_159));
  OAI112BHD g8052__9945(.A1 (tpreset[0]), .B1 (tmax[0]), .C1
       (tpreset[1]), .C2 (tmax[1]), .O (n_157));
  AOI13BHD g8053__2883(.A1 (tpreset[6]), .B1 (tpreset[5]), .B2
       (tmax[5]), .B3 (tmax[6]), .O (n_156));
  AOI13BHD g8054__2346(.A1 (vbat[3]), .B1 (vbat[0]), .B2 (vbat[2]), .B3
       (vbat[1]), .O (n_155));
  OAI112BHD g8055__1666(.A1 (n_124), .B1 (n_103), .C1 (n_72), .C2
       (vbat[0]), .O (n_154));
  OAI222BHD g8056__7410(.A1 (tmax[5]), .A2 (tpreset[5]), .B1
       (tpreset[4]), .B2 (tmax[4]), .C1 (tmax[6]), .C2 (tpreset[6]), .O
       (n_158));
  INVDHD g8057(.I (n_316), .O (n_150));
  ND2CHD g8058__6417(.I1 (n_128), .I2 (tempmin[6]), .O (n_149));
  AN2B1CHD g8059__5477(.I1 (tempmin[4]), .B1 (n_113), .O (n_148));
  AN2CHD g8060__2398(.I1 (n_111), .I2 (vcutoff[1]), .O (n_147));
  OAI12CHD g8061__5107(.A1 (tempmax[0]), .B1 (n_71), .B2 (tempmax[1]),
       .O (n_146));
  OR2B1CHD g8062__6260(.I1 (tempmax[4]), .B1 (n_132), .O (n_145));
  OAI12CHD g8063__4319(.A1 (n_101), .B1 (tpreset[10]), .B2 (n_70), .O
       (n_153));
  ND2DHD g8064__8428(.I1 (n_1651_BAR), .I2 (current_state[0]), .O
       (n_232));
  OAI12CHD g8065__5526(.A1 (n_128), .B1 (n_87), .B2 (tempmin[6]), .O
       (n_152));
  OAI12CHD g8066__6783(.A1 (n_129), .B1 (n_74), .B2 (tbat[6]), .O
       (n_151));
  OR2EHD g8067__3680(.I1 (current_state[0]), .I2 (n_131), .O (n_314));
  OR2B1CHD g8068__1617(.I1 (n_233), .B1 (current_state[0]), .O (n_315));
  OR2B1CHD g8069__2802(.I1 (n_131), .B1 (current_state[0]), .O (n_316));
  OAI22CHD g8070__1705(.A1 (vpreset[5]), .A2 (n_83), .B1 (n_64), .B2
       (vpreset[6]), .O (n_137));
  AOI12CHD g8071__5122(.A1 (tmax[6]), .B1 (tpreset[5]), .B2 (tmax[5]),
       .O (n_136));
  AOI12CHD g8072__8246(.A1 (tempmin[0]), .B1 (n_71), .B2 (tempmin[1]),
       .O (n_135));
  MAOI1CHD g8073__7098(.A1 (tpreset[7]), .A2 (tmax[7]), .B1 (tmax[0]),
       .B2 (tpreset[8]), .O (n_134));
  AOI22BHD g8074__6131(.A1 (tpreset[3]), .A2 (tmax[3]), .B1
       (tpreset[4]), .B2 (tmax[4]), .O (n_133));
  OAI12CHD g8075__1881(.A1 (n_111), .B1 (n_78), .B2 (vcutoff[1]), .O
       (n_144));
  OAI12CHD g8076__5115(.A1 (n_118), .B1 (tpreset[12]), .B2 (n_86), .O
       (n_143));
  OAI12CHD g8077__7482(.A1 (n_119), .B1 (tpreset[11]), .B2 (n_84), .O
       (n_142));
  OAI12CHD g8078__4733(.A1 (n_102), .B1 (tpreset[13]), .B2 (n_77), .O
       (n_141));
  MOAI1CHD g8079__6161(.A1 (tpreset[9]), .A2 (tmax[1]), .B1
       (tpreset[9]), .B2 (tmax[1]), .O (n_140));
  OAI12CHD g8080__9315(.A1 (n_117), .B1 (tpreset[14]), .B2 (n_79), .O
       (n_139));
  AOI22BHD g8081__9945(.A1 (n_82), .A2 (vpreset[2]), .B1 (n_65), .B2
       (vpreset[3]), .O (n_138));
  ND2CHD g8082__2883(.I1 (n_85), .I2 (tempmin[7]), .O (n_116));
  ND2CHD g8083__2346(.I1 (n_66), .I2 (tempmax[5]), .O (n_132));
  OR2B1CHD g8084__1666(.I1 (current_state[2]), .B1 (current_state[1]),
       .O (n_131));
  OR2B1CHD g8085__7410(.I1 (vbat[7]), .B1 (vpreset[7]), .O (n_130));
  ND2CHD g8086__6417(.I1 (n_85), .I2 (tempmax[7]), .O (n_129));
  OR2CHD g8087__5477(.I1 (tempmin[7]), .I2 (n_85), .O (n_128));
  OR2B1CHD g8088__2398(.I1 (ibat[0]), .B1 (iend[0]), .O (n_115));
  ND2CHD g8089__5107(.I1 (n_81), .I2 (vpreset[4]), .O (n_127));
  AN2CHD g8090__6260(.I1 (n_81), .I2 (vcutoff[4]), .O (n_126));
  AN2B1CHD g8091__4319(.I1 (tmax[7]), .B1 (tpreset[15]), .O (n_125));
  ND2CHD g8092__8428(.I1 (n_64), .I2 (vpreset[6]), .O (n_124));
  OR2B1CHD g8093__5526(.I1 (vbat[7]), .B1 (vcutoff[7]), .O (n_123));
  OR2B1CHD g8094__6783(.I1 (tmax[1]), .B1 (tpreset[9]), .O (n_122));
  AN2CHD g8095__3680(.I1 (n_64), .I2 (vcutoff[6]), .O (n_121));
  ND2CHD g8096__1617(.I1 (n_83), .I2 (vcutoff[5]), .O (n_120));
  ND2CHD g8097__2802(.I1 (n_65), .I2 (vpreset[3]), .O (n_114));
  ND2CHD g8098__1705(.I1 (tpreset[11]), .I2 (n_84), .O (n_119));
  ND2CHD g8099__5122(.I1 (tpreset[12]), .I2 (n_86), .O (n_118));
  ND2CHD g8100__8246(.I1 (tpreset[14]), .I2 (n_79), .O (n_117));
  INVDHD g8101(.I (n_107), .O (n_108));
  AN2CHD g8102__7098(.I1 (n_67), .I2 (tempmin[3]), .O (n_100));
  ND2CHD g8103__6131(.I1 (n_91), .I2 (tbat[3]), .O (n_99));
  OR2B1CHD g8104__1881(.I1 (tmax[7]), .B1 (tpreset[15]), .O (n_98));
  ND2DHD g8105__5115(.I1 (tpreset[1]), .I2 (tmax[1]), .O (n_97));
  ND2CHD g8106__7482(.I1 (tpreset[8]), .I2 (tmax[0]), .O (n_96));
  AN2EHD g8107__4733(.I1 (tpreset[2]), .I2 (tmax[2]), .O (n_95));
  NR2CHD g8108__6161(.I1 (current_state[2]), .I2 (current_state[1]), .O
       (n_1651_BAR));
  NR2BHD g8109__9315(.I1 (tempmin[5]), .I2 (n_66), .O (n_113));
  ND2CHD g8110__9945(.I1 (n_78), .I2 (vpreset[1]), .O (n_112));
  OR2CHD g8111__2883(.I1 (vcutoff[2]), .I2 (n_82), .O (n_111));
  NR2BHD g8112__2346(.I1 (vcutoff[7]), .I2 (n_80), .O (n_110));
  NR2BHD g8113__1666(.I1 (vpreset[7]), .I2 (n_80), .O (n_109));
  NR2BHD g8114__7410(.I1 (vcutoff[3]), .I2 (n_65), .O (n_107));
  OR2CHD g8115__6417(.I1 (vcutoff[6]), .I2 (n_64), .O (n_106));
  OR2CHD g8116__5477(.I1 (vcutoff[4]), .I2 (n_81), .O (n_105));
  NR2BHD g8117__2398(.I1 (vcutoff[5]), .I2 (n_83), .O (n_104));
  ND2CHD g8118__5107(.I1 (n_83), .I2 (vpreset[5]), .O (n_103));
  ND2CHD g8119__6260(.I1 (tpreset[13]), .I2 (n_77), .O (n_102));
  ND2CHD g8120__4319(.I1 (tpreset[10]), .I2 (n_70), .O (n_101));
  OR2B1CHD g8121__8428(.I1 (current_state[1]), .B1 (current_state[2]),
       .O (n_233));
  INVDHD g8122(.I (iend[5]), .O (n_94));
  INVDHD g8123(.I (iend[3]), .O (n_93));
  INVDHD g8124(.I (iend[6]), .O (n_92));
  INVDHD g8125(.I (tempmax[3]), .O (n_91));
  INVDHD g8126(.I (tempmax[1]), .O (n_90));
  INVDHD g8127(.I (iend[4]), .O (n_89));
  INVDHD g8128(.I (tempmin[1]), .O (n_88));
  INVDHD g8129(.I (tbat[6]), .O (n_87));
  INVDHD g8130(.I (tmax[4]), .O (n_86));
  INVDHD g8131(.I (tbat[7]), .O (n_85));
  INVDHD g8132(.I (tmax[3]), .O (n_84));
  INVDHD g8133(.I (vbat[5]), .O (n_83));
  INVDHD g8134(.I (vbat[2]), .O (n_82));
  INVDHD g8135(.I (vbat[4]), .O (n_81));
  INVDHD g8136(.I (vbat[7]), .O (n_80));
  INVDHD g8137(.I (tmax[6]), .O (n_79));
  INVDHD g8138(.I (vbat[1]), .O (n_78));
  INVDHD g8139(.I (tmax[5]), .O (n_77));
  INVDHD g8140(.I (iend[2]), .O (n_76));
  INVDHD g8141(.I (iend[1]), .O (n_75));
  INVDHD g8142(.I (tempmax[6]), .O (n_74));
  INVDHD g8143(.I (vpreset[3]), .O (n_73));
  INVDHD g8144(.I (vpreset[0]), .O (n_72));
  INVDHD g8145(.I (tbat[1]), .O (n_71));
  INVDHD g8146(.I (tmax[2]), .O (n_70));
  INVDHD g8147(.I (tbat[4]), .O (n_69));
  INVDHD g8148(.I (tbat[2]), .O (n_68));
  INVDHD g8149(.I (tbat[3]), .O (n_67));
  INVDHD g8150(.I (tbat[5]), .O (n_66));
  INVDHD g8151(.I (vbat[3]), .O (n_65));
  INVDHD g8152(.I (vbat[6]), .O (n_64));
  QDFZHHD \current_state_reg[0] (.CK (clk), .D (n_40), .TD (si), .SEL
       (se), .Q (current_state[0]));
  QDFZHHD \current_state_reg[1] (.CK (clk), .D (n_35), .TD
       (current_state[0]), .SEL (se), .Q (current_state[1]));
  QDFZHHD \current_state_reg[2] (.CK (clk), .D (n_37), .TD
       (current_state[1]), .SEL (se), .Q (current_state[2]));
  QDFZHHD \tpreset_reg[0] (.CK (clk), .D (n_15), .TD
       (current_state[2]), .SEL (se), .Q (tpreset[0]));
  DFZCRBEHD \tpreset_reg[1] (.CK (clk), .D (n_23), .RB (n_32), .TD
       (tpreset[0]), .SEL (se), .Q (tpreset[1]), .QB (n_14));
  DFZCRBEHD \tpreset_reg[2] (.CK (clk), .D (n_34), .RB (n_32), .TD
       (n_14), .SEL (se), .Q (tpreset[2]), .QB (n_13));
  DFZCRBEHD \tpreset_reg[3] (.CK (clk), .D (n_39), .RB (n_32), .TD
       (n_13), .SEL (se), .Q (tpreset[3]), .QB (n_12));
  DFZCRBEHD \tpreset_reg[4] (.CK (clk), .D (n_42), .RB (n_32), .TD
       (n_12), .SEL (se), .Q (tpreset[4]), .QB (n_11));
  DFZCRBEHD \tpreset_reg[5] (.CK (clk), .D (n_44), .RB (n_32), .TD
       (n_11), .SEL (se), .Q (tpreset[5]), .QB (n_10));
  DFZCRBEHD \tpreset_reg[6] (.CK (clk), .D (n_46), .RB (n_32), .TD
       (n_10), .SEL (se), .Q (tpreset[6]), .QB (n_9));
  DFZCRBEHD \tpreset_reg[7] (.CK (clk), .D (n_48), .RB (n_32), .TD
       (n_9), .SEL (se), .Q (tpreset[7]), .QB (n_8));
  DFZCRBEHD \tpreset_reg[8] (.CK (clk), .D (n_50), .RB (n_32), .TD
       (n_8), .SEL (se), .Q (tpreset[8]), .QB (n_7));
  DFZCRBEHD \tpreset_reg[9] (.CK (clk), .D (n_52), .RB (n_32), .TD
       (n_7), .SEL (se), .Q (tpreset[9]), .QB (n_6));
  DFZCRBEHD \tpreset_reg[10] (.CK (clk), .D (n_54), .RB (n_32), .TD
       (n_6), .SEL (se), .Q (tpreset[10]), .QB (n_5));
  DFZCRBEHD \tpreset_reg[11] (.CK (clk), .D (n_56), .RB (n_32), .TD
       (n_5), .SEL (se), .Q (tpreset[11]), .QB (n_4));
  DFZCRBEHD \tpreset_reg[12] (.CK (clk), .D (n_58), .RB (n_32), .TD
       (n_4), .SEL (se), .Q (tpreset[12]), .QB (n_3));
  DFZCRBEHD \tpreset_reg[13] (.CK (clk), .D (n_60), .RB (n_32), .TD
       (n_3), .SEL (se), .Q (tpreset[13]), .QB (n_2));
  DFZCRBEHD \tpreset_reg[14] (.CK (clk), .D (n_62), .RB (n_32), .TD
       (n_2), .SEL (se), .Q (tpreset[14]), .QB (n_1));
  DFZCRBEHD \tpreset_reg[15] (.CK (clk), .D (n_63), .RB (n_32), .TD
       (n_1), .SEL (se), .Q (tpreset[15]), .QB (so));
  MOAI1CHD g5506__5526(.A1 (n_61), .A2 (tpreset[15]), .B1 (n_61), .B2
       (tpreset[15]), .O (n_63));
  MOAI1CHD g5508__6783(.A1 (n_59), .A2 (tpreset[14]), .B1 (n_59), .B2
       (tpreset[14]), .O (n_62));
  OR2B1CHD g5509__3680(.I1 (n_59), .B1 (tpreset[14]), .O (n_61));
  MOAI1CHD g5511__1617(.A1 (n_57), .A2 (tpreset[13]), .B1 (n_57), .B2
       (tpreset[13]), .O (n_60));
  OR2B1CHD g5512__2802(.I1 (n_57), .B1 (tpreset[13]), .O (n_59));
  MOAI1CHD g5514__1705(.A1 (n_55), .A2 (tpreset[12]), .B1 (n_55), .B2
       (tpreset[12]), .O (n_58));
  OR2B1CHD g5515__5122(.I1 (n_55), .B1 (tpreset[12]), .O (n_57));
  MOAI1CHD g5517__8246(.A1 (n_53), .A2 (tpreset[11]), .B1 (n_53), .B2
       (tpreset[11]), .O (n_56));
  OR2B1CHD g5518__7098(.I1 (n_53), .B1 (tpreset[11]), .O (n_55));
  MOAI1CHD g5520__6131(.A1 (n_51), .A2 (tpreset[10]), .B1 (n_51), .B2
       (tpreset[10]), .O (n_54));
  OR2B1CHD g5521__1881(.I1 (n_51), .B1 (tpreset[10]), .O (n_53));
  MOAI1CHD g5523__5115(.A1 (n_49), .A2 (tpreset[9]), .B1 (n_49), .B2
       (tpreset[9]), .O (n_52));
  OR2B1CHD g5524__7482(.I1 (n_49), .B1 (tpreset[9]), .O (n_51));
  MOAI1CHD g5526__4733(.A1 (n_47), .A2 (tpreset[8]), .B1 (n_47), .B2
       (tpreset[8]), .O (n_50));
  OR2B1CHD g5527__6161(.I1 (n_47), .B1 (tpreset[8]), .O (n_49));
  MOAI1CHD g5529__9315(.A1 (n_45), .A2 (tpreset[7]), .B1 (n_45), .B2
       (tpreset[7]), .O (n_48));
  OR2B1CHD g5530__9945(.I1 (n_45), .B1 (tpreset[7]), .O (n_47));
  MOAI1CHD g5532__2883(.A1 (n_43), .A2 (tpreset[6]), .B1 (n_43), .B2
       (tpreset[6]), .O (n_46));
  OR2B1CHD g5533__2346(.I1 (n_43), .B1 (tpreset[6]), .O (n_45));
  MOAI1CHD g5535__1666(.A1 (n_41), .A2 (tpreset[5]), .B1 (n_41), .B2
       (tpreset[5]), .O (n_44));
  OR2B1CHD g5536__7410(.I1 (n_41), .B1 (tpreset[5]), .O (n_43));
  MOAI1CHD g5538__6417(.A1 (n_38), .A2 (tpreset[4]), .B1 (n_38), .B2
       (tpreset[4]), .O (n_42));
  OR2B1CHD g5539__5477(.I1 (n_38), .B1 (tpreset[4]), .O (n_41));
  ND3CHD g5542__2398(.I1 (n_36), .I2 (n_27), .I3 (n_28), .O (n_40));
  MOAI1CHD g5543__5107(.A1 (n_33), .A2 (tpreset[3]), .B1 (n_33), .B2
       (tpreset[3]), .O (n_39));
  OR2B1CHD g5545__6260(.I1 (n_33), .B1 (tpreset[3]), .O (n_38));
  OAI112BHD g5548__4319(.A1 (n_31), .B1 (n_25), .C1 (n_237), .C2
       (n_20), .O (n_37));
  AOI222BHD g5549__8428(.A1 (n_30), .A2 (rstz), .B1 (n_318), .B2
       (n_24), .C1 (n_18), .C2 (n_21), .O (n_36));
  OAI112BHD g5552__5526(.A1 (n_29), .B1 (n_28), .C1 (n_317), .C2
       (n_27), .O (n_35));
  MOAI1CHD g5553__6783(.A1 (n_19), .A2 (tpreset[2]), .B1 (n_19), .B2
       (tpreset[2]), .O (n_34));
  OR2B1CHD g5554__3680(.I1 (n_19), .B1 (tpreset[2]), .O (n_33));
  MAOI1CHD g5556__1617(.A1 (n_317), .A2 (n_26), .B1 (n_22), .B2
       (n_236), .O (n_31));
  ND3CHD g5557__2802(.I1 (n_20), .I2 (n_25), .I3 (n_22), .O (n_32));
  OAI22CHD g5558__1705(.A1 (n_17), .A2 (current_state[0]), .B1 (n_232),
       .B2 (n_231), .O (n_30));
  AOI22BHD g5559__5122(.A1 (n_237), .A2 (n_21), .B1 (n_235), .B2
       (rstz), .O (n_29));
  INVDHD g5560(.I (n_27), .O (n_26));
  OR2B1CHD g5561__8246(.I1 (n_22), .B1 (n_236), .O (n_28));
  OR3B2CHD g5562__7098(.I1 (n_315), .B1 (n_234), .B2 (rstz), .O (n_27));
  INVDHD g5563(.I (n_24), .O (n_25));
  XOR2EHD g5564__6131(.I1 (tpreset[0]), .I2 (tpreset[1]), .O (n_23));
  NR3BHD g5565__1881(.I1 (n_16), .I2 (current_state[0]), .I3 (n_233),
       .O (n_24));
  INVDHD g5566(.I (n_21), .O (n_20));
  OR2EHD g5567__5115(.I1 (n_16), .I2 (n_316), .O (n_22));
  NR2CHD g5568__7482(.I1 (n_16), .I2 (n_314), .O (n_21));
  ND2CHD g5569__4733(.I1 (n_238), .I2 (n_237), .O (n_18));
  ND2DHD g5570__6161(.I1 (n_1651_BAR), .I2 (en), .O (n_17));
  ND2DHD g5571__9315(.I1 (tpreset[0]), .I2 (tpreset[1]), .O (n_19));
  INVDHD g5591(.I (rstz), .O (n_16));
  AN2B1CHD g2__9945(.I1 (n_32), .B1 (tpreset[0]), .O (n_15));
endmodule

