
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Dec  9 2024 22:44:57 WET (Dec  9 2024 22:44:57 UTC)

// Verification Directory fv/BATCHARGER_controller 

module BATCHARGER_controller(cc, tc, cv, imonen, vmonen, tmonen, vtok,
     vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax, tmax, iend,
     clk, en, rstz, dvdd, dgnd, se, si, so);
  input vtok, clk, en, rstz, se, si;
  input [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  output cc, tc, cv, imonen, vmonen, tmonen, so;
  inout dvdd, dgnd;
  wire vtok, clk, en, rstz, se, si;
  wire [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  wire cc, tc, cv, imonen, vmonen, tmonen, so;
  wire dvdd, dgnd;
  wire [2:0] current_state;
  wire [15:0] tpreset;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_17;
  wire n_18, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_83, n_84, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_142, n_143, n_144, n_145, n_146, n_147, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_210, n_211, n_212, n_217, n_218, n_219, n_220;
  wire n_221, n_222, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_242, n_243, n_244, n_245, n_246, n_247;
  wire n_248, n_249, n_250, n_251, n_252, n_253, n_254, n_255;
  wire n_256, n_257, n_258, n_259, n_260, n_261, n_262, n_263;
  wire n_264, n_265, n_266, n_267, n_268, n_269, n_270, n_271;
  wire n_272, n_273, n_274, n_275, n_276, n_277, n_278, n_280;
  wire n_281, n_360, n_361;
  assign imonen = cv;
  QDFZRBEHD \current_state_reg[0] (.RB (rstz), .CK (clk), .D (n_281),
       .TD (si), .SEL (se), .Q (current_state[0]));
  QDFZRBEHD \current_state_reg[1] (.RB (rstz), .CK (clk), .D (n_278),
       .TD (current_state[0]), .SEL (se), .Q (current_state[1]));
  OAI13BHD g1686__2398(.A1 (n_280), .B1 (n_269), .B2 (n_2), .B3
       (current_state[2]), .O (n_281));
  QDFZRBEHD \current_state_reg[2] (.RB (rstz), .CK (clk), .D (n_276),
       .TD (current_state[1]), .SEL (se), .Q (current_state[2]));
  ND2CHD g1687__5107(.I1 (n_277), .I2 (n_2), .O (n_280));
  OAI13BHD g1684__6260(.A1 (n_275), .B1 (n_272), .B2 (n_2), .B3
       (current_state[2]), .O (n_278));
  AOI22BHD g1694__4319(.A1 (n_270), .A2 (current_state[2]), .B1
       (n_260), .B2 (n_271), .O (n_277));
  OAI22CHD g1685__8428(.A1 (current_state[1]), .A2 (n_274), .B1
       (n_273), .B2 (n_2), .O (n_276));
  OAI112BHD g1688__5526(.A1 (n_274), .B1 (n_2), .C1 (n_257), .C2
       (current_state[2]), .O (n_275));
  ND2CHD g1693__6783(.I1 (n_272), .I2 (n_271), .O (n_273));
  OAI22CHD g1710__3680(.A1 (current_state[0]), .A2 (n_267), .B1
       (n_259), .B2 (n_264), .O (n_270));
  AO12EHD g1700__1617(.A1 (n_271), .B1 (n_265), .B2 (current_state[0]),
       .O (n_274));
  OAI13BHD g1701__2802(.A1 (n_268), .B1 (n_266), .B2
       (current_state[0]), .B3 (n_189), .O (n_269));
  OAI12CHD g1702__1705(.A1 (n_268), .B1 (current_state[0]), .B2
       (n_190), .O (n_272));
  OAI12CHD g1714__5122(.A1 (n_263), .B1 (n_243), .B2 (n_182), .O
       (n_267));
  ND2CHD g1707__8246(.I1 (n_266), .I2 (current_state[0]), .O (n_268));
  OAI13BHD g1712__7098(.A1 (n_264), .B1 (n_258), .B2 (n_244), .B3
       (n_171), .O (n_265));
  MOAI1CHD g1724__6131(.A1 (n_262), .A2 (n_261), .B1 (n_262), .B2
       (n_261), .O (n_263));
  OAI22CHD g1709__1881(.A1 (n_256), .A2 (n_259), .B1
       (current_state[0]), .B2 (en), .O (n_260));
  INVCKDHD g1721(.I (n_258), .O (n_266));
  QDFZRBEHD \tpreset_reg[11] (.RB (rstz), .CK (clk), .D (n_255), .TD
       (tpreset[10]), .SEL (se), .Q (tpreset[11]));
  QDFZRBEHD \tpreset_reg[15] (.RB (rstz), .CK (clk), .D (n_251), .TD
       (tpreset[14]), .SEL (se), .Q (so));
  NR2BHD g1713__5115(.I1 (n_256), .I2 (n_259), .O (n_257));
  AO2222BHD g1723__7482(.A1 (n_254), .A2 (n_248), .B1 (n_202), .B2
       (n_139), .C1 (n_164), .C2 (n_169), .D1 (n_247), .D2 (n_211), .O
       (n_258));
  QDFZRBEHD \tpreset_reg[13] (.RB (rstz), .CK (clk), .D (n_249), .TD
       (tpreset[12]), .SEL (se), .Q (tpreset[13]));
  AOI112BHD g1746__4733(.A1 (n_253), .B1 (n_239), .C1 (n_252), .C2
       (n_234), .O (n_262));
  QDFZRBEHD \tpreset_reg[9] (.RB (rstz), .CK (clk), .D (n_246), .TD
       (tpreset[8]), .SEL (se), .Q (tpreset[9]));
  QDFZRBEHD \tpreset_reg[10] (.RB (rstz), .CK (clk), .D (n_242), .TD
       (tpreset[9]), .SEL (se), .Q (tpreset[10]));
  QDFZRBEHD \tpreset_reg[14] (.RB (rstz), .CK (clk), .D (n_238), .TD
       (tpreset[13]), .SEL (se), .Q (tpreset[14]));
  OR3B1CHD g1718__6161(.I1 (n_153), .I2 (n_160), .B1 (n_245), .O
       (n_256));
  QDFZRBEHD \tpreset_reg[12] (.RB (rstz), .CK (clk), .D (n_240), .TD
       (tpreset[11]), .SEL (se), .Q (tpreset[12]));
  QDFZRBEHD \tpreset_reg[7] (.RB (rstz), .CK (clk), .D (n_237), .TD
       (tpreset[6]), .SEL (se), .Q (tpreset[7]));
  QDFZRBEHD \tpreset_reg[8] (.RB (rstz), .CK (clk), .D (n_236), .TD
       (tpreset[7]), .SEL (se), .Q (tpreset[8]));
  MUXB2CHD g1678__9315(.S (n_219), .A (n_64), .B (tpreset[11]), .EB
       (n_250), .O (n_255));
  OAI112BHD g1737__9945(.A1 (n_235), .B1 (n_206), .C1 (n_149), .C2
       (vbat[3]), .O (n_254));
  OA112EHD g1764__2883(.A1 (n_252), .B1 (n_198), .C1 (n_179), .C2
       (n_196), .O (n_253));
  QDFZRBEHD \tpreset_reg[6] (.RB (rstz), .CK (clk), .D (n_212), .TD
       (tpreset[5]), .SEL (se), .Q (tpreset[6]));
  QDFZRBEHD \tpreset_reg[0] (.RB (rstz), .CK (clk), .D (n_220), .TD
       (current_state[2]), .SEL (se), .Q (tpreset[0]));
  QDFZRBEHD \tpreset_reg[3] (.RB (rstz), .CK (clk), .D (n_229), .TD
       (tpreset[2]), .SEL (se), .Q (tpreset[3]));
  MUXB2CHD g1682__2346(.S (n_222), .A (so), .B (n_58), .EB (n_250), .O
       (n_251));
  MUXB2CHD g1680__1666(.S (n_218), .A (n_57), .B (tpreset[13]), .EB
       (n_250), .O (n_249));
  AO2222BHD g1720__7410(.A1 (n_204), .A2 (n_136), .B1 (n_41), .B2
       (n_40), .C1 (n_134), .C2 (vbat[7]), .D1 (n_135), .D2 (n_143), .O
       (n_264));
  QDFZRBEHD \tpreset_reg[2] (.RB (rstz), .CK (clk), .D (n_231), .TD
       (tpreset[1]), .SEL (se), .Q (tpreset[2]));
  QDFZRBEHD \tpreset_reg[1] (.RB (rstz), .CK (clk), .D (n_207), .TD
       (tpreset[0]), .SEL (se), .Q (tpreset[1]));
  QDFZRBEHD \tpreset_reg[4] (.RB (rstz), .CK (clk), .D (n_226), .TD
       (tpreset[3]), .SEL (se), .Q (tpreset[4]));
  QDFZRBEHD \tpreset_reg[5] (.RB (rstz), .CK (clk), .D (n_225), .TD
       (tpreset[4]), .SEL (se), .Q (tpreset[5]));
  OA112EHD g1745__6417(.A1 (n_247), .B1 (n_210), .C1 (n_360), .C2
       (n_208), .O (n_248));
  MUXB2CHD g1668__5477(.S (n_199), .A (n_46), .B (tpreset[9]), .EB
       (n_250), .O (n_246));
  AOI22BHD g1722__2398(.A1 (n_227), .A2 (n_162), .B1 (n_230), .B2
       (n_148), .O (n_245));
  AN4B1BHD g1727__5107(.I1 (n_228), .I2 (n_110), .I3 (n_36), .B1
       (n_170), .O (n_244));
  AN4B1BHD g1728__6260(.I1 (n_232), .I2 (n_112), .I3 (n_29), .B1
       (n_181), .O (n_243));
  MUXB2CHD g1677__4319(.S (n_188), .A (tpreset[10]), .B (n_65), .EB
       (n_250), .O (n_242));
  MUXB2CHD g1679__5526(.S (n_194), .A (tpreset[12]), .B (n_45), .EB
       (n_250), .O (n_240));
  OAI222BHD g1795__6783(.A1 (n_175), .A2 (n_233), .B1 (n_167), .B2
       (n_186), .C1 (n_115), .C2 (n_116), .O (n_239));
  MUXB2CHD g1681__3680(.S (n_185), .A (tpreset[14]), .B (n_56), .EB
       (n_250), .O (n_238));
  NR2BHD g1674__1617(.I1 (n_250), .I2 (n_201), .O (n_237));
  MUXB2CHD g1675__2802(.S (tpreset[8]), .A (n_221), .B (n_193), .EB
       (n_250), .O (n_236));
  OAI112BHD g1772__1705(.A1 (n_205), .B1 (n_177), .C1 (n_180), .C2
       (n_156), .O (n_235));
  OAI222BHD g1815__5122(.A1 (n_101), .A2 (n_197), .B1 (n_158), .B2
       (n_122), .C1 (n_117), .C2 (n_118), .O (n_234));
  NR3BHD g1660__8246(.I1 (current_state[0]), .I2 (current_state[1]),
       .I3 (n_271), .O (cv));
  AOI112BHD g1818__7098(.A1 (n_233), .B1 (n_174), .C1 (n_173), .C2
       (n_172), .O (n_252));
  OAI112BHD g1735__6131(.A1 (n_159), .B1 (n_81), .C1 (n_33), .C2
       (iend[3]), .O (n_232));
  MUXB2CHD g1669__1881(.S (n_59), .A (n_60), .B (tpreset[2]), .EB
       (n_250), .O (n_231));
  OAI112BHD g1739__5115(.A1 (n_163), .B1 (n_78), .C1 (n_32), .C2
       (tempmax[3]), .O (n_230));
  NR2BHD g1670__7482(.I1 (n_145), .I2 (n_250), .O (n_229));
  OAI112BHD g1742__4733(.A1 (n_154), .B1 (n_72), .C1 (n_203), .C2
       (vpreset[3]), .O (n_228));
  OAI112BHD g1743__6161(.A1 (n_151), .B1 (n_75), .C1 (n_31), .C2
       (tbat[3]), .O (n_227));
  MUXB2CHD g1671__9315(.S (n_140), .A (n_105), .B (tpreset[4]), .EB
       (n_250), .O (n_226));
  NR2BHD g1672__9945(.I1 (n_250), .I2 (n_192), .O (n_225));
  AN4B1BHD g1699__2346(.I1 (n_221), .I2 (n_184), .I3 (tpreset[14]), .B1
       (n_217), .O (n_222));
  NR2BHD g1676__1666(.I1 (tpreset[0]), .I2 (n_250), .O (n_220));
  OR3B2CHD g1703__7410(.I1 (n_187), .B1 (n_221), .B2 (tpreset[10]), .O
       (n_219));
  OR3B2CHD g1704__6417(.I1 (n_217), .B1 (n_221), .B2 (tpreset[12]), .O
       (n_218));
  NR3BHD g1658__5477(.I1 (current_state[2]), .I2 (n_2), .I3 (n_259), .O
       (cc));
  NR3BHD g1657__2398(.I1 (current_state[2]), .I2 (current_state[0]),
       .I3 (n_2), .O (tc));
  MUXB2CHD g1673__5107(.S (n_114), .A (tpreset[6]), .B (n_195), .EB
       (n_250), .O (n_212));
  AO13EHD g1773__6260(.A1 (n_152), .B1 (n_210), .B2 (n_360), .B3
       (n_208), .O (n_211));
  MUXB2CHD g1683__4319(.S (tpreset[1]), .A (tpreset[0]), .B (n_0), .EB
       (n_250), .O (n_207));
  OR3B2CHD g1788__8428(.I1 (vbat[2]), .B1 (n_205), .B2 (n_176), .O
       (n_206));
  OAI112BHD g1726__5526(.A1 (n_161), .B1 (n_96), .C1 (n_203), .C2
       (vcutoff[3]), .O (n_204));
  OA12EHD g1775__6783(.A1 (n_202), .B1 (n_138), .B2 (n_137), .O
       (n_247));
  MAOI1CHD g1691__3680(.A1 (n_200), .A2 (tpreset[7]), .B1 (tpreset[7]),
       .B2 (n_200), .O (n_201));
  ND2CHD g1866__1617(.I1 (n_221), .I2 (tpreset[8]), .O (n_199));
  NR2BHD g1813__2802(.I1 (n_52), .I2 (n_197), .O (n_198));
  OAI222BHD g1816__1705(.A1 (n_178), .A2 (n_124), .B1 (n_23), .B2
       (n_28), .C1 (n_55), .C2 (n_195), .O (n_196));
  NR2BHD g1697__5122(.I1 (n_217), .I2 (n_193), .O (n_194));
  MAOI1CHD g1690__8246(.A1 (n_191), .A2 (tpreset[5]), .B1 (tpreset[5]),
       .B2 (n_191), .O (n_192));
  INVCKDHD g1717(.I (n_189), .O (n_190));
  NR2BHD g1696__7098(.I1 (n_187), .I2 (n_193), .O (n_188));
  OA13EHD g1843__6131(.A1 (n_127), .B1 (n_168), .B2 (n_166), .B3
       (n_165), .O (n_186));
  AN3B2BHD g1706__1881(.I1 (n_184), .B1 (n_193), .B2 (n_217), .O
       (n_185));
  OAI222BHD g1692__5115(.A1 (vmonen), .A2 (n_259), .B1 (n_2), .B2
       (vmonen), .C1 (current_state[2]), .C2 (current_state[1]), .O
       (n_250));
  OAI112BHD g1730__7482(.A1 (n_102), .B1 (n_18), .C1 (n_113), .C2
       (n_181), .O (n_182));
  AOI22BHD g1811__4733(.A1 (n_123), .A2 (vbat[0]), .B1 (n_155), .B2
       (vbat[1]), .O (n_180));
  AOI112BHD g1812__6161(.A1 (n_178), .B1 (n_93), .C1 (n_126), .C2
       (n_128), .O (n_179));
  OR2B1CHD g1814__9315(.I1 (n_176), .B1 (vbat[2]), .O (n_177));
  OA13EHD g1828__9945(.A1 (n_129), .B1 (n_174), .B2 (n_173), .B3
       (n_172), .O (n_175));
  OAI222BHD g1731__2883(.A1 (n_35), .A2 (n_86), .B1 (n_111), .B2
       (n_170), .C1 (vpreset[7]), .C2 (n_169), .O (n_171));
  AO112CHD g1829__2346(.A1 (n_168), .B1 (n_167), .C1 (n_166), .C2
       (n_165), .O (n_233));
  OR2EHD g1786__1666(.I1 (n_169), .I2 (n_164), .O (n_202));
  OAI112BHD g1770__7410(.A1 (n_67), .B1 (n_77), .C1 (n_76), .C2
       (tbat[2]), .O (n_163));
  OA112CHD g1741__6417(.A1 (n_100), .B1 (n_97), .C1 (n_146), .C2
       (tempmin[4]), .O (n_162));
  OAI112BHD g1744__5477(.A1 (n_89), .B1 (n_95), .C1 (n_130), .C2
       (vbat[2]), .O (n_161));
  OAI112BHD g1734__2398(.A1 (n_53), .B1 (n_22), .C1 (n_88), .C2
       (n_147), .O (n_160));
  OAI112BHD g1769__5107(.A1 (n_69), .B1 (n_80), .C1 (n_79), .C2
       (ibat[2]), .O (n_159));
  AO12EHD g1838__6260(.A1 (n_158), .B1 (n_120), .B2 (n_121), .O
       (n_197));
  INVDHD g1869(.I (n_193), .O (n_221));
  NR2BHD g1817__4319(.I1 (vbat[1]), .I2 (n_155), .O (n_156));
  OAI112BHD g1774__8428(.A1 (n_84), .B1 (n_71), .C1 (n_70), .C2
       (vbat[2]), .O (n_154));
  OAI112BHD g1733__5526(.A1 (n_94), .B1 (n_17), .C1 (n_98), .C2 (n_99),
       .O (n_153));
  NR2CHD g1789__6783(.I1 (vbat[5]), .I2 (n_150), .O (n_152));
  OAI112BHD g1771__3680(.A1 (n_68), .B1 (n_74), .C1 (n_73), .C2
       (tempmin[2]), .O (n_151));
  ND2CHD g1820__1617(.I1 (n_150), .I2 (vbat[5]), .O (n_210));
  ND2DHD g1819__2802(.I1 (n_149), .I2 (vbat[3]), .O (n_205));
  AOI12CHD g1719__1705(.A1 (n_37), .B1 (n_361), .B2 (n_142), .O
       (n_189));
  AOI112BHD g1738__5122(.A1 (n_147), .B1 (n_87), .C1 (n_146), .C2
       (tempmax[4]), .O (n_148));
  MAOI1CHD g1689__8246(.A1 (n_144), .A2 (tpreset[3]), .B1 (tpreset[3]),
       .B2 (n_144), .O (n_145));
  OAI12CHD g1736__7098(.A1 (n_91), .B1 (n_142), .B2 (vcutoff[5]), .O
       (n_143));
  OR3EHD g1870__6131(.I1 (n_26), .I2 (n_133), .I3 (n_140), .O (n_193));
  AN2EHD g1794__1881(.I1 (n_138), .I2 (n_137), .O (n_139));
  OA112CHD g1732__5115(.A1 (n_135), .B1 (n_90), .C1 (n_131), .C2
       (vbat[4]), .O (n_136));
  AOI22BHD g1821__7482(.A1 (n_63), .A2 (1'b1), .B1 (n_2), .B2 (n_134),
       .O (n_164));
  OR3EHD g1705__4733(.I1 (n_195), .I2 (n_133), .I3 (n_140), .O (n_200));
  AOI22BHD g1832__9315(.A1 (n_62), .A2 (current_state[1]), .B1 (n_2),
       .B2 (n_130), .O (n_176));
  ND2CHD g1834__9945(.I1 (n_108), .I2 (n_109), .O (n_129));
  OAI112BHD g1836__2883(.A1 (n_125), .B1 (n_10), .C1 (tpreset[1]), .C2
       (tmax[1]), .O (n_128));
  ND2CHD g1851__2346(.I1 (n_106), .I2 (n_107), .O (n_127));
  AOI22BHD g1841__1666(.A1 (n_125), .A2 (n_25), .B1 (tpreset[2]), .B2
       (tmax[2]), .O (n_126));
  AOI22BHD g1844__7410(.A1 (n_92), .A2 (n_13), .B1 (tpreset[4]), .B2
       (tmax[4]), .O (n_124));
  OAI22CHD g1845__6417(.A1 (n_2), .A2 (n_44), .B1 (current_state[1]),
       .B2 (vcutoff[0]), .O (n_123));
  OR2EHD g1850__5477(.I1 (n_121), .I2 (n_120), .O (n_122));
  MUX3EHD g1846__2398(.S0 (current_state[0]), .S1 (n_2), .A (n_119), .B
       (n_83), .C (n_119), .O (n_155));
  AN2EHD g1857__5107(.I1 (n_118), .I2 (n_117), .O (n_158));
  AN2EHD g1837__6260(.I1 (n_116), .I2 (n_115), .O (n_167));
  NR2BHD g1695__4319(.I1 (n_133), .I2 (n_140), .O (n_114));
  AOI22BHD g1755__8428(.A1 (n_24), .A2 (n_112), .B1 (n_30), .B2
       (ibat[5]), .O (n_113));
  MAOI1CHD g1768__5526(.A1 (n_110), .A2 (n_34), .B1 (vpreset[5]), .B2
       (n_142), .O (n_111));
  NR2CHD g1858__6783(.I1 (n_109), .I2 (n_108), .O (n_174));
  OAI22CHD g1833__3680(.A1 (n_2), .A2 (n_43), .B1 (current_state[1]),
       .B2 (vcutoff[5]), .O (n_150));
  NR2CHD g1865__1617(.I1 (n_107), .I2 (n_106), .O (n_168));
  OR2EHD g1867__2802(.I1 (n_105), .I2 (n_140), .O (n_191));
  OAI22CHD g1831__1705(.A1 (n_2), .A2 (n_42), .B1 (current_state[1]),
       .B2 (vcutoff[3]), .O (n_149));
  OR3B2CHD g1756__5122(.I1 (iend[6]), .B1 (n_47), .B2 (ibat[6]), .O
       (n_102));
  AOI13BHD g1842__8246(.A1 (n_27), .B1 (n_51), .B2 (tpreset[7]), .B3
       (tmax[7]), .O (n_101));
  INVCKDHD g1747(.I (n_99), .O (n_100));
  AOI13BHD g1748__7098(.A1 (n_12), .B1 (n_97), .B2 (n_146), .B3
       (tempmin[4]), .O (n_98));
  ND3CHD g1767__6131(.I1 (n_95), .I2 (n_130), .I3 (vbat[2]), .O (n_96));
  OR3B2CHD g1753__1881(.I1 (tbat[6]), .B1 (n_50), .B2 (tempmin[6]), .O
       (n_94));
  OAI12CHD g1835__5115(.A1 (n_92), .B1 (tpreset[3]), .B2 (tmax[3]), .O
       (n_93));
  ND3CHD g1765__7482(.I1 (n_90), .I2 (n_131), .I3 (vbat[4]), .O (n_91));
  MAO222CHD g1762__4733(.A1 (n_11), .B1 (n_119), .C1 (vbat[1]), .O
       (n_89));
  OA13CHD g1763__6161(.A1 (n_8), .B1 (n_87), .B2 (n_146), .B3
       (tempmax[4]), .O (n_88));
  AO12CHD g1759__9315(.A1 (n_86), .B1 (n_137), .B2 (vpreset[6]), .O
       (n_170));
  MAO222CHD g1796__9945(.A1 (n_21), .B1 (n_83), .C1 (vbat[1]), .O
       (n_84));
  ND3CHD g1790__2346(.I1 (n_80), .I2 (n_79), .I3 (ibat[2]), .O (n_81));
  ND3CHD g1791__1666(.I1 (n_77), .I2 (n_76), .I3 (tbat[2]), .O (n_78));
  ND3CHD g1792__7410(.I1 (n_74), .I2 (n_73), .I3 (tempmin[2]), .O
       (n_75));
  ND3CHD g1793__6417(.I1 (n_71), .I2 (n_70), .I3 (vbat[2]), .O (n_72));
  MAO222CHD g1799__5477(.A1 (n_9), .B1 (n_3), .C1 (ibat[1]), .O (n_69));
  MAO222CHD g1797__2398(.A1 (n_14), .B1 (n_1), .C1 (tempmin[1]), .O
       (n_68));
  MAO222CHD g1798__5107(.A1 (n_15), .B1 (n_6), .C1 (tbat[1]), .O
       (n_67));
  MUX3EHD g1822__6260(.S0 (current_state[0]), .S1 (n_2), .A
       (vcutoff[6]), .B (vpreset[6]), .C (vcutoff[6]), .O (n_138));
  NR2CHD g1708__4319(.I1 (current_state[2]), .I2 (n_2), .O (vmonen));
  OR3EHD g1711__8428(.I1 (n_65), .I2 (n_64), .I3 (n_187), .O (n_217));
  OAI22CHD g1840__5526(.A1 (vcutoff[7]), .A2 (current_state[0]), .B1
       (n_259), .B2 (vpreset[7]), .O (n_63));
  OAI22CHD g1853__6783(.A1 (vcutoff[2]), .A2 (current_state[0]), .B1
       (n_259), .B2 (vpreset[2]), .O (n_62));
  OAI22CHD g1855__3680(.A1 (vcutoff[4]), .A2 (current_state[0]), .B1
       (n_259), .B2 (vpreset[4]), .O (n_61));
  AOI22BHD g1740__1617(.A1 (n_137), .A2 (vcutoff[6]), .B1 (n_169), .B2
       (vcutoff[7]), .O (n_135));
  OR2EHD g1868__2802(.I1 (n_60), .I2 (n_59), .O (n_144));
  MXL2CHD g1885__1705(.S (tmax[7]), .A (n_58), .B (so), .OB (n_116));
  MXL2CHD g1881__5122(.S (tmax[3]), .A (n_64), .B (tpreset[11]), .OB
       (n_173));
  MXL2CHD g1882__8246(.S (tmax[5]), .A (n_57), .B (tpreset[13]), .OB
       (n_166));
  OAI22CHD g1884__7098(.A1 (tmax[6]), .A2 (tpreset[14]), .B1 (n_56),
       .B2 (n_55), .O (n_106));
  OR3B2CHD g1871__6131(.I1 (n_59), .B1 (tpreset[2]), .B2 (tpreset[3]),
       .O (n_140));
  ND3CHD g1766__1881(.I1 (n_49), .I2 (n_48), .I3 (tbat[6]), .O (n_53));
  OAI12CHD g1827__5115(.A1 (n_51), .B1 (tpreset[7]), .B2 (tmax[7]), .O
       (n_52));
  OAI12CHD g1757__7482(.A1 (n_50), .B1 (n_5), .B2 (tempmin[6]), .O
       (n_99));
  OAI12CHD g1758__4733(.A1 (n_49), .B1 (n_48), .B2 (tbat[6]), .O
       (n_147));
  OAI12CHD g1761__6161(.A1 (n_47), .B1 (n_4), .B2 (ibat[6]), .O
       (n_181));
  MUX2EHD g1887__9315(.S (tmax[1]), .A (tpreset[9]), .B (n_46), .O
       (n_120));
  MXL2CHD g1883__9945(.S (tmax[4]), .A (tpreset[12]), .B (n_45), .OB
       (n_108));
  MUX2EHD g1886__2883(.S (tmax[2]), .A (tpreset[10]), .B (n_65), .O
       (n_118));
  MUX2EHD g1862__2346(.S (current_state[0]), .A (vcutoff[0]), .B
       (vpreset[0]), .O (n_44));
  MUX2CHD g1856__1666(.S (current_state[0]), .A (vcutoff[5]), .B
       (vpreset[5]), .O (n_43));
  MUX2CHD g1854__7410(.S (current_state[0]), .A (vcutoff[3]), .B
       (vpreset[3]), .O (n_42));
  ND2CHD g1760__6417(.I1 (n_169), .I2 (vcutoff[7]), .O (n_41));
  NR2BHD g1752__5477(.I1 (vcutoff[6]), .I2 (n_137), .O (n_40));
  OAI22CHD g1839__2398(.A1 (tmax[5]), .A2 (tpreset[5]), .B1
       (tpreset[6]), .B2 (tmax[6]), .O (n_178));
  OR2B1CHD g1864__5107(.I1 (tmax[2]), .B1 (n_60), .O (n_125));
  ND2CHD g1875__6260(.I1 (tpreset[14]), .I2 (n_55), .O (n_115));
  NR2CHD g1877__4319(.I1 (tmax[3]), .I2 (n_64), .O (n_109));
  NR2CHD g1878__8428(.I1 (tmax[5]), .I2 (n_57), .O (n_107));
  OR2B1CHD g1861__5526(.I1 (tmax[4]), .B1 (n_105), .O (n_92));
  OAI112BHD g1725__6783(.A1 (vbat[7]), .B1 (vbat[6]), .C1 (vbat[5]),
       .C2 (vbat[4]), .O (n_37));
  ND2CHD g1779__3680(.I1 (n_208), .I2 (vpreset[4]), .O (n_36));
  OR2CHD g1777__1617(.I1 (vpreset[6]), .I2 (n_137), .O (n_35));
  NR2BHD g1802__2802(.I1 (vpreset[4]), .I2 (n_208), .O (n_34));
  ND2CHD g1787__1705(.I1 (n_142), .I2 (vcutoff[5]), .O (n_90));
  AN2CHD g1785__5122(.I1 (n_169), .I2 (vpreset[7]), .O (n_86));
  ND2CHD g1803__8246(.I1 (n_33), .I2 (iend[3]), .O (n_80));
  ND2CHD g1804__7098(.I1 (n_142), .I2 (vpreset[5]), .O (n_110));
  ND2CHD g1805__6131(.I1 (n_32), .I2 (tempmax[3]), .O (n_77));
  ND2CHD g1806__1881(.I1 (n_203), .I2 (vpreset[3]), .O (n_71));
  ND2CHD g1809__5115(.I1 (n_31), .I2 (tbat[3]), .O (n_74));
  OR2CHD g1810__7482(.I1 (ibat[5]), .I2 (n_30), .O (n_112));
  ND2CHD g1784__4733(.I1 (n_203), .I2 (vcutoff[3]), .O (n_95));
  NR2CHD g1715__6161(.I1 (n_45), .I2 (n_57), .O (n_184));
  OR2B1CHD g1778__9315(.I1 (ibat[4]), .B1 (iend[4]), .O (n_29));
  ND2DHD g1848__9945(.I1 (tpreset[5]), .I2 (tmax[5]), .O (n_28));
  NR2CHD g1849__2883(.I1 (tmax[0]), .I2 (tpreset[8]), .O (n_27));
  ND2CHD g1873__2346(.I1 (tpreset[6]), .I2 (tpreset[7]), .O (n_26));
  AN2EHD g1860__1666(.I1 (tpreset[1]), .I2 (tmax[1]), .O (n_25));
  AN2B1CHD g1800__7410(.I1 (ibat[4]), .B1 (iend[4]), .O (n_24));
  NR2BHD g1852__6417(.I1 (tmax[6]), .I2 (tpreset[6]), .O (n_23));
  OR2B1CHD g1750__5477(.I1 (tempmax[7]), .B1 (tbat[7]), .O (n_22));
  OR2B1CHD g1826__2398(.I1 (vbat[0]), .B1 (vpreset[0]), .O (n_21));
  OR2B1CHD g1751__6260(.I1 (iend[7]), .B1 (ibat[7]), .O (n_18));
  OR2B1CHD g1749__4319(.I1 (tbat[7]), .B1 (tempmin[7]), .O (n_17));
  OR2B1CHD g1879__8428(.I1 (tmax[2]), .B1 (tpreset[10]), .O (n_172));
  OR2B1CHD g1874__5526(.I1 (tmax[4]), .B1 (tpreset[12]), .O (n_165));
  ND2CHD g1872__6783(.I1 (tpreset[4]), .I2 (tpreset[5]), .O (n_133));
  ND2CHD g1888__3680(.I1 (tpreset[0]), .I2 (tpreset[1]), .O (n_59));
  OR2B1CHD g1824__1617(.I1 (tbat[0]), .B1 (tempmax[0]), .O (n_15));
  OR2B1CHD g1825__2802(.I1 (tempmin[0]), .B1 (tbat[0]), .O (n_14));
  AN2EHD g1859__1705(.I1 (tpreset[3]), .I2 (tmax[3]), .O (n_13));
  AN2B1CHD g1776__5122(.I1 (tempmin[5]), .B1 (tbat[5]), .O (n_12));
  OR2B1CHD g1801__8246(.I1 (vbat[0]), .B1 (vcutoff[0]), .O (n_11));
  AN2EHD g1847__7098(.I1 (tpreset[0]), .I2 (tmax[0]), .O (n_10));
  OR2B1CHD g1823__6131(.I1 (ibat[0]), .B1 (iend[0]), .O (n_9));
  OR2B1CHD g1780__1881(.I1 (tempmax[5]), .B1 (tbat[5]), .O (n_8));
  OR2B1CHD g1782__5115(.I1 (tbat[7]), .B1 (tempmax[7]), .O (n_49));
  OR2B1CHD g1783__7482(.I1 (tempmin[7]), .B1 (tbat[7]), .O (n_50));
  OR2B1CHD g1880__4733(.I1 (tmax[7]), .B1 (so), .O (n_261));
  OR2B1CHD g1807__6161(.I1 (tempmin[5]), .B1 (tbat[5]), .O (n_97));
  AN2B1CHD g1808__9315(.I1 (tempmax[5]), .B1 (tbat[5]), .O (n_87));
  ND2CHD g1863__9945(.I1 (tpreset[8]), .I2 (tmax[0]), .O (n_51));
  OR2B1CHD g1876__2883(.I1 (tmax[1]), .B1 (tpreset[9]), .O (n_117));
  OR2B1CHD g1781__2346(.I1 (ibat[7]), .B1 (iend[7]), .O (n_47));
  ND2CHD g1716__1666(.I1 (tpreset[8]), .I2 (tpreset[9]), .O (n_187));
  INVCKDHD g1889(.I (tempmax[1]), .O (n_6));
  INVCKDHD g1893(.I (tbat[6]), .O (n_5));
  INVCKDHD g1906(.I (iend[6]), .O (n_4));
  INVCKDHD g1903(.I (iend[2]), .O (n_79));
  INVDHD g1918(.I (so), .O (n_58));
  INVCKDHD g1894(.I (tbat[2]), .O (n_73));
  INVDHD g1898(.I (tpreset[9]), .O (n_46));
  INVDHD g1900(.I (tpreset[8]), .O (n_121));
  INVCKDHD g1908(.I (ibat[3]), .O (n_33));
  INVCKDHD g1915(.I (tbat[3]), .O (n_32));
  INVCKDHD g1910(.I (tempmax[6]), .O (n_48));
  INVCKDHD g1916(.I (vcutoff[2]), .O (n_130));
  INVCKDHD g1914(.I (vcutoff[1]), .O (n_119));
  INVCKDHD g1917(.I (tmax[6]), .O (n_55));
  INVDHD g1920(.I (tpreset[2]), .O (n_60));
  INVDHD g1899(.I (tpreset[12]), .O (n_45));
  INVCKDHD g1897(.I (tpreset[4]), .O (n_105));
  INVDHD g1901(.I (current_state[2]), .O (n_271));
  INVCKDHD g1891(.I (tbat[4]), .O (n_146));
  INVCKDHD g1926(.I (vbat[6]), .O (n_137));
  INVDHD g1902(.I (current_state[0]), .O (n_259));
  INVCKDHD g1904(.I (iend[1]), .O (n_3));
  INVCKDHD g1892(.I (tbat[1]), .O (n_1));
  INVDHD g1919(.I (tpreset[0]), .O (n_0));
  INVDHD g1939(.I (current_state[1]), .O (n_2));
  INVCKDHD g1913(.I (vcutoff[7]), .O (n_134));
  INVCKDHD g1890(.I (vpreset[2]), .O (n_70));
  INVCKDHD g1907(.I (iend[5]), .O (n_30));
  INVCKDHD g1905(.I (tempmin[3]), .O (n_31));
  INVCKDHD g1909(.I (tempmax[2]), .O (n_76));
  INVCKDHD g1911(.I (vpreset[1]), .O (n_83));
  INVDHD g1921(.I (tpreset[14]), .O (n_56));
  INVDHD g1924(.I (tpreset[10]), .O (n_65));
  INVCKDHD g1912(.I (vcutoff[4]), .O (n_131));
  INVDHD g1896(.I (tpreset[6]), .O (n_195));
  INVCKDHD g1923(.I (vbat[4]), .O (n_208));
  INVCKDHD g1927(.I (vbat[3]), .O (n_203));
  INVDHD g1895(.I (tpreset[13]), .O (n_57));
  INVDHD g1922(.I (tpreset[11]), .O (n_64));
  INVCKDHD g1928(.I (vbat[5]), .O (n_142));
  INVCKDHD g1925(.I (vbat[7]), .O (n_169));
  MXL2CHD g2(.S (current_state[1]), .A (n_131), .B (n_61), .OB (n_360));
  AOI13BHD g1965(.A1 (vbat[3]), .B1 (vbat[1]), .B2 (vbat[0]), .B3
       (vbat[2]), .O (n_361));
  AN3B2BHD g1966(.I1 (current_state[0]), .B1 (current_state[2]), .B2
       (current_state[1]), .O (tmonen));
endmodule

