
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Dec 10 2024 11:07:37 WET (Dec 10 2024 11:07:37 UTC)

// Verification Directory fv/BATCHARGER_controller 

module BATCHARGER_controller(cc, tc, cv, imonen, vmonen, tmonen, vtok,
     vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax, tmax, iend,
     clk, en, rstz, dvdd, dgnd, si, se, so);
  input vtok, clk, en, rstz, si, se;
  input [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  output cc, tc, cv, imonen, vmonen, tmonen, so;
  inout dvdd, dgnd;
  wire vtok, clk, en, rstz, si, se;
  wire [7:0] vbat, ibat, tbat, vcutoff, vpreset, tempmin, tempmax,
       tmax, iend;
  wire cc, tc, cv, imonen, vmonen, tmonen, so;
  wire dvdd, dgnd;
  wire [2:0] current_state;
  wire [15:0] tpreset;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_20, n_21, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_98;
  wire n_99, n_100, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_242, n_243, n_244, n_246, n_247, n_248;
  wire n_249, n_250, n_252, n_253, n_254, n_255, n_256, n_257;
  wire n_258, n_259, n_260, n_261, n_262, n_263, n_264, n_265;
  wire n_266, n_267, n_268, n_347, n_348, n_349, n_350, n_351;
  wire n_352;
  assign imonen = cv;
  DFZCRBEHD \current_state_reg[0] (.CK (clk), .D (n_268), .RB (rstz),
       .TD (si), .SEL (se), .Q (current_state[0]), .QB (n_12));
  QDFZHHD \current_state_reg[2] (.CK (clk), .D (n_266), .TD (n_11),
       .SEL (se), .Q (current_state[2]));
  OAI13BHD g1331__2398(.A1 (n_267), .B1 (n_265), .B2 (n_261), .B3
       (n_262), .O (n_268));
  DFZCRBEHD \current_state_reg[1] (.CK (clk), .D (n_260), .RB (rstz),
       .TD (n_12), .SEL (se), .Q (current_state[1]), .QB (n_11));
  OAI112BHD g1344__5107(.A1 (n_264), .B1 (n_241), .C1
       (current_state[0]), .C2 (en), .O (n_267));
  AN2EHD g1324__6260(.I1 (n_263), .I2 (rstz), .O (n_266));
  INVDHD g1359(.I (n_264), .O (n_265));
  OAI112BHD g1361__4319(.A1 (n_254), .B1 (current_state[2]), .C1
       (n_253), .C2 (current_state[0]), .O (n_264));
  OAI13BHD g1334__8428(.A1 (n_259), .B1 (n_262), .B2
       (current_state[0]), .B3 (n_255), .O (n_263));
  OAI13BHD g1360__5526(.A1 (n_252), .B1 (n_347), .B2 (n_249), .B3
       (n_248), .O (n_261));
  OAI13BHD g1333__6783(.A1 (n_258), .B1 (n_256), .B2 (n_257), .B3
       (n_246), .O (n_260));
  OR2B1CHD g1343__3680(.I1 (n_262), .B1 (n_250), .O (n_259));
  OR3B1EHD g1345__1617(.I1 (n_257), .I2 (n_256), .B1 (n_255), .O
       (n_258));
  OR2B1CHD g1363__2802(.I1 (n_253), .B1 (n_247), .O (n_254));
  OR3B2CHD g1365__1705(.I1 (n_347), .B1 (current_state[1]), .B2
       (n_255), .O (n_252));
  AO13EHD g1351__5122(.A1 (n_256), .B1 (n_249), .B2 (n_248), .B3
       (n_247), .O (n_250));
  OA112EHD g1371__8246(.A1 (n_244), .B1 (n_246), .C1 (n_224), .C2
       (n_174), .O (n_253));
  AO13EHD g1358__6131(.A1 (n_239), .B1 (n_249), .B2 (current_state[2]),
       .B3 (n_247), .O (n_257));
  AOI22BHD g1362__1881(.A1 (n_249), .A2 (current_state[0]), .B1 (n_58),
       .B2 (n_62), .O (n_256));
  MOAI1CHD g1381__5115(.A1 (n_243), .A2 (n_242), .B1 (n_243), .B2
       (n_242), .O (n_244));
  AOI13BHD g1357__7482(.A1 (current_state[1]), .B1 (current_state[0]),
       .B2 (n_238), .B3 (n_237), .O (n_241));
  DFZCRBEHD \tpreset_reg[13] (.CK (clk), .D (n_232), .RB (n_240), .TD
       (tpreset[12]), .SEL (se), .Q (tpreset[13]), .QB (n_10));
  DFZCRBEHD \tpreset_reg[11] (.CK (clk), .D (n_234), .RB (n_240), .TD
       (tpreset[10]), .SEL (se), .Q (tpreset[11]), .QB (n_9));
  AOI13BHD g1366__4733(.A1 (n_99), .B1 (n_248), .B2 (n_238), .B3
       (n_237), .O (n_239));
  QDFZHHD \tpreset_reg[14] (.CK (clk), .D (n_236), .TD (n_10), .SEL
       (se), .Q (tpreset[14]));
  AO2222CHD g1478__6161(.A1 (n_235), .A2 (n_209), .B1 (n_166), .B2
       (n_141), .C1 (n_133), .C2 (n_134), .D1 (n_208), .D2 (n_193), .O
       (n_249));
  QDFZHHD \tpreset_reg[12] (.CK (clk), .D (n_226), .TD (n_9), .SEL
       (se), .Q (tpreset[12]));
  QDFZHHD \tpreset_reg[10] (.CK (clk), .D (n_230), .TD (n_7), .SEL
       (se), .Q (tpreset[10]));
  AOI112BHD g1417__9315(.A1 (n_228), .B1 (n_219), .C1 (n_227), .C2
       (n_210), .O (n_243));
  DFZCRBEHD \tpreset_reg[15] (.CK (clk), .D (n_221), .RB (n_240), .TD
       (tpreset[14]), .SEL (se), .Q (tpreset[15]), .QB (so));
  DFZCRBEHD \tpreset_reg[9] (.CK (clk), .D (n_218), .RB (n_240), .TD
       (tpreset[8]), .SEL (se), .Q (tpreset[9]), .QB (n_7));
  QDFZHHD \tpreset_reg[8] (.CK (clk), .D (n_222), .TD (n_6), .SEL (se),
       .Q (tpreset[8]));
  MUXB2CHD g1329__9945(.S (n_215), .A (tpreset[14]), .B (n_144), .EB
       (n_229), .O (n_236));
  DFZCRBEHD \tpreset_reg[7] (.CK (clk), .D (n_205), .RB (n_240), .TD
       (tpreset[6]), .SEL (se), .Q (tpreset[7]), .QB (n_6));
  OAI112BHD g1479__2883(.A1 (n_216), .B1 (n_178), .C1 (n_136), .C2
       (n_135), .O (n_235));
  NR2BHD g1374__2346(.I1 (n_168), .I2 (n_223), .O (n_238));
  NR2BHD g1369__1666(.I1 (n_181), .I2 (n_225), .O (n_237));
  MOAI1CHD g1339__7410(.A1 (n_233), .A2 (tpreset[11]), .B1 (n_233), .B2
       (tpreset[11]), .O (n_234));
  MOAI1CHD g1340__6417(.A1 (n_231), .A2 (tpreset[13]), .B1 (n_231), .B2
       (tpreset[13]), .O (n_232));
  QDFZHHD \tpreset_reg[6] (.CK (clk), .D (n_202), .TD (n_5), .SEL (se),
       .Q (tpreset[6]));
  DFZCRBEHD \tpreset_reg[5] (.CK (clk), .D (n_187), .RB (n_240), .TD
       (n_0), .SEL (se), .Q (tpreset[5]), .QB (n_5));
  MUXB2CHD g1327__5477(.S (n_200), .A (tpreset[10]), .B (n_213), .EB
       (n_229), .O (n_230));
  OA112EHD g1429__2398(.A1 (n_227), .B1 (n_196), .C1 (n_183), .C2
       (n_185), .O (n_228));
  MUXB2CHD g1328__5107(.S (n_198), .A (tpreset[12]), .B (n_212), .EB
       (n_229), .O (n_226));
  AO2222BHD g1370__6260(.A1 (n_201), .A2 (n_159), .B1 (n_100), .B2
       (n_350), .C1 (n_54), .C2 (vbat[7]), .D1 (n_158), .D2 (n_147), .O
       (n_247));
  AN4B1BHD g1373__4319(.I1 (n_197), .I2 (n_128), .I3 (n_28), .B1
       (n_180), .O (n_225));
  AN4B1BHD g1378__8428(.I1 (n_203), .I2 (n_131), .I3 (n_37), .B1
       (n_173), .O (n_224));
  AN4B1BHD g1379__5526(.I1 (n_206), .I2 (n_126), .I3 (n_36), .B1
       (n_167), .O (n_223));
  MUXB2CHD g1326__6783(.S (tpreset[8]), .A (n_194), .B (n_214), .EB
       (n_229), .O (n_222));
  MOAI1CHD g1342__3680(.A1 (n_220), .A2 (tpreset[15]), .B1 (n_220), .B2
       (tpreset[15]), .O (n_221));
  DFZCRBEHD \tpreset_reg[3] (.CK (clk), .D (n_240), .RB (n_157), .TD
       (n_2), .SEL (se), .Q (tpreset[3]), .QB (n_4));
  DFZCRBEHD \tpreset_reg[1] (.CK (clk), .D (n_240), .RB (n_61), .TD
       (n_1), .SEL (se), .Q (tpreset[1]), .QB (n_3));
  DFZCRBEHD \tpreset_reg[2] (.CK (clk), .D (n_240), .RB (n_348), .TD
       (n_3), .SEL (se), .Q (tpreset[2]), .QB (n_2));
  OAI222BHD g1437__1617(.A1 (n_207), .A2 (n_155), .B1 (n_172), .B2
       (n_179), .C1 (n_76), .C2 (n_77), .O (n_219));
  MOAI1CHD g1338__2802(.A1 (n_217), .A2 (tpreset[9]), .B1 (n_217), .B2
       (tpreset[9]), .O (n_218));
  OAI112BHD g1482__1705(.A1 (n_188), .B1 (n_177), .C1 (n_176), .C2
       (n_175), .O (n_216));
  DFZCRBEHD \tpreset_reg[0] (.CK (clk), .D (n_240), .RB (tpreset[0]),
       .TD (current_state[2]), .SEL (se), .Q (n_1), .QB (tpreset[0]));
  DFZCRBEHD \tpreset_reg[4] (.CK (clk), .D (n_240), .RB (n_165), .TD
       (n_4), .SEL (se), .Q (tpreset[4]), .QB (n_0));
  NR3BHD g1353__5122(.I1 (n_143), .I2 (n_211), .I3 (n_214), .O (n_215));
  OR3EHD g1352__8246(.I1 (n_213), .I2 (n_199), .I3 (n_214), .O (n_233));
  OR3EHD g1355__7098(.I1 (n_212), .I2 (n_211), .I3 (n_214), .O (n_231));
  OAI222BHD g1444__6131(.A1 (n_85), .A2 (n_195), .B1 (n_150), .B2
       (n_82), .C1 (n_118), .C2 (n_119), .O (n_210));
  OA112EHD g1480__1881(.A1 (n_208), .B1 (n_192), .C1 (n_190), .C2
       (n_189), .O (n_209));
  AOI112BHD g1447__5115(.A1 (n_207), .B1 (n_154), .C1 (n_153), .C2
       (n_152), .O (n_227));
  OAI112BHD g1392__7482(.A1 (n_160), .B1 (n_96), .C1 (n_48), .C2
       (tbat[3]), .O (n_206));
  MOAI1CHD g1341__4733(.A1 (n_204), .A2 (tpreset[7]), .B1 (n_204), .B2
       (tpreset[7]), .O (n_205));
  OAI112BHD g1391__6161(.A1 (n_161), .B1 (n_93), .C1 (n_47), .C2
       (iend[3]), .O (n_203));
  MUXB2CHD g1325__9315(.S (n_149), .A (tpreset[6]), .B (n_184), .EB
       (n_229), .O (n_202));
  OAI112BHD g1377__9945(.A1 (n_162), .B1 (n_109), .C1 (n_72), .C2
       (vcutoff[3]), .O (n_201));
  NR2BHD g1347__2883(.I1 (n_199), .I2 (n_214), .O (n_200));
  NR2BHD g1346__2346(.I1 (n_211), .I2 (n_214), .O (n_198));
  OAI112BHD g1383__1666(.A1 (n_163), .B1 (n_112), .C1 (n_49), .C2
       (tempmax[3]), .O (n_197));
  NR2CHD g1446__7410(.I1 (n_69), .I2 (n_195), .O (n_196));
  ND2CHD g1349__6417(.I1 (n_194), .I2 (n_145), .O (n_220));
  ND2CHD g1497__5477(.I1 (n_194), .I2 (tpreset[8]), .O (n_217));
  AO13EHD g1483__2398(.A1 (n_142), .B1 (n_192), .B2 (n_190), .B3
       (n_189), .O (n_193));
  MAO222EHD g1487__5107(.A1 (n_148), .B1 (n_104), .C1 (n_59), .O
       (n_188));
  MOAI1CHD g1337__6260(.A1 (n_186), .A2 (tpreset[5]), .B1 (n_186), .B2
       (tpreset[5]), .O (n_187));
  OAI222BHD g1445__4319(.A1 (n_182), .A2 (n_86), .B1 (n_26), .B2
       (n_32), .C1 (n_73), .C2 (n_184), .O (n_185));
  AOI112BHD g1443__8428(.A1 (n_182), .B1 (n_71), .C1 (n_83), .C2
       (n_124), .O (n_183));
  OAI112BHD g1376__5526(.A1 (n_117), .B1 (n_30), .C1 (n_129), .C2
       (n_180), .O (n_181));
  AO112CHD g1450__6783(.A1 (n_171), .B1 (n_179), .C1 (n_170), .C2
       (n_169), .O (n_207));
  INVDHD g1512(.I (n_194), .O (n_214));
  ND3CHD g1486__3680(.I1 (n_177), .I2 (n_176), .I3 (n_175), .O (n_178));
  OAI112BHD g1385__1617(.A1 (n_67), .B1 (n_43), .C1 (n_132), .C2
       (n_173), .O (n_174));
  OA13EHD g1460__2802(.A1 (n_125), .B1 (n_171), .B2 (n_170), .B3
       (n_169), .O (n_172));
  OAI112BHD g1384__1705(.A1 (n_106), .B1 (n_40), .C1 (n_127), .C2
       (n_167), .O (n_168));
  OA12EHD g1481__5122(.A1 (n_166), .B1 (n_140), .B2 (n_139), .O
       (n_208));
  MOAI1CHD g1505__8246(.A1 (n_164), .A2 (tpreset[4]), .B1 (n_164), .B2
       (tpreset[4]), .O (n_165));
  OAI112BHD g1394__7098(.A1 (n_116), .B1 (n_111), .C1 (n_110), .C2
       (tbat[2]), .O (n_163));
  OAI112BHD g1395__6131(.A1 (n_98), .B1 (n_108), .C1 (n_107), .C2
       (vbat[2]), .O (n_162));
  OAI112BHD g1414__1881(.A1 (n_84), .B1 (n_92), .C1 (n_91), .C2
       (ibat[2]), .O (n_161));
  OAI112BHD g1413__5115(.A1 (n_90), .B1 (n_95), .C1 (n_94), .C2
       (tempmin[2]), .O (n_160));
  NR3BHD g1514__7482(.I1 (n_29), .I2 (n_151), .I3 (n_164), .O (n_194));
  OA112CHD g1382__4733(.A1 (n_158), .B1 (n_114), .C1 (n_113), .C2
       (vbat[4]), .O (n_159));
  MOAI1CHD g1332__6161(.A1 (n_156), .A2 (tpreset[3]), .B1 (n_156), .B2
       (tpreset[3]), .O (n_157));
  OA13EHD g1449__9315(.A1 (n_89), .B1 (n_154), .B2 (n_153), .B3
       (n_152), .O (n_155));
  OR3EHD g1354__9945(.I1 (n_184), .I2 (n_151), .I3 (n_164), .O (n_204));
  AO12EHD g1455__2883(.A1 (n_150), .B1 (n_80), .B2 (n_81), .O (n_195));
  AO12CHD g1372__2346(.A1 (n_53), .B1 (n_349), .B2 (n_146), .O (n_255));
  INVDHD g1330(.I (n_229), .O (n_240));
  NR2BHD g1348__1666(.I1 (n_151), .I2 (n_164), .O (n_149));
  OR2B1CHD g1495__7410(.I1 (n_60), .B1 (n_105), .O (n_148));
  OAI12CHD g1393__6417(.A1 (n_115), .B1 (n_146), .B2 (vcutoff[5]), .O
       (n_147));
  NR3BHD g1356__5477(.I1 (n_144), .I2 (n_143), .I3 (n_211), .O (n_145));
  OR2B1CHD g1507__2398(.I1 (n_164), .B1 (tpreset[4]), .O (n_186));
  AN2B1CHD g1484__5107(.I1 (n_138), .B1 (n_137), .O (n_142));
  AN2EHD g1485__6260(.I1 (n_140), .I2 (n_139), .O (n_141));
  OR2B1CHD g1490__4319(.I1 (n_138), .B1 (n_137), .O (n_192));
  ND2DHD g1489__8428(.I1 (n_136), .I2 (n_135), .O (n_177));
  OR2EHD g1488__5526(.I1 (n_134), .I2 (n_133), .O (n_166));
  AO12EHD g1336__6783(.A1 (n_262), .B1 (n_351), .B2 (current_state[0]),
       .O (n_229));
  AOI22BHD g1409__3680(.A1 (n_34), .A2 (n_131), .B1 (n_46), .B2
       (ibat[5]), .O (n_132));
  AOI22BHD g1388__2802(.A1 (n_35), .A2 (n_128), .B1 (n_15), .B2
       (tbat[5]), .O (n_129));
  AOI22BHD g1412__1705(.A1 (n_39), .A2 (n_126), .B1 (n_50), .B2
       (tempmin[5]), .O (n_127));
  ND2CHD g1465__5122(.I1 (n_120), .I2 (n_121), .O (n_125));
  OAI112BHD g1458__8246(.A1 (n_52), .B1 (n_25), .C1 (tpreset[1]), .C2
       (tmax[1]), .O (n_124));
  OAI12CHD g1313__7098(.A1 (n_351), .B1 (n_102), .B2 (n_246), .O
       (vmonen));
  NR2CHD g1475__6131(.I1 (n_121), .I2 (n_120), .O (n_171));
  AN2EHD g1466__1881(.I1 (n_119), .I2 (n_118), .O (n_150));
  OR3B2CHD g1387__5115(.I1 (tempmax[6]), .B1 (n_75), .B2 (tbat[6]), .O
       (n_117));
  MAO222CHD g1415__7482(.A1 (n_27), .B1 (n_20), .C1 (tbat[1]), .O
       (n_116));
  ND3CHD g1411__4733(.I1 (n_114), .I2 (n_113), .I3 (vbat[4]), .O
       (n_115));
  ND3CHD g1410__6161(.I1 (n_111), .I2 (n_110), .I3 (tbat[2]), .O
       (n_112));
  ND3CHD g1407__9315(.I1 (n_108), .I2 (n_107), .I3 (vbat[2]), .O
       (n_109));
  OR3B2CHD g1397__9945(.I1 (tbat[6]), .B1 (n_74), .B2 (tempmin[6]), .O
       (n_106));
  AOI222BHD g1508__2883(.A1 (current_state[2]), .A2 (vbat[0]), .B1
       (n_103), .B2 (vpreset[0]), .C1 (n_246), .C2 (vcutoff[0]), .O
       (n_105));
  AO222EHD g1509__2346(.A1 (current_state[2]), .A2 (vbat[1]), .B1
       (n_103), .B2 (vpreset[1]), .C1 (n_246), .C2 (vcutoff[1]), .O
       (n_104));
  AO222EHD g1498__1666(.A1 (current_state[2]), .A2 (vbat[2]), .B1
       (n_103), .B2 (vpreset[2]), .C1 (n_246), .C2 (vcutoff[2]), .O
       (n_176));
  NR2BHD g1316__7410(.I1 (current_state[0]), .I2 (n_102), .O (cv));
  ND2CHD g1511__6417(.I1 (n_352), .I2 (tpreset[2]), .O (n_156));
  AO222EHD g1500__5477(.A1 (current_state[2]), .A2 (vbat[4]), .B1
       (n_103), .B2 (vpreset[4]), .C1 (n_246), .C2 (vcutoff[4]), .O
       (n_190));
  AOI222BHD g1503__2398(.A1 (current_state[2]), .A2 (vbat[3]), .B1
       (n_103), .B2 (vpreset[3]), .C1 (n_246), .C2 (vcutoff[3]), .O
       (n_136));
  AOI222BHD g1501__5107(.A1 (current_state[2]), .A2 (vbat[5]), .B1
       (n_103), .B2 (vpreset[5]), .C1 (n_246), .C2 (vcutoff[5]), .O
       (n_137));
  AN2CHD g1390__6260(.I1 (n_100), .I2 (n_38), .O (n_158));
  INVDHD g1517(.I (n_99), .O (n_262));
  ND3CHD g1515__4319(.I1 (n_352), .I2 (tpreset[2]), .I3 (tpreset[3]),
       .O (n_164));
  MAO222CHD g1416__8428(.A1 (n_44), .B1 (n_13), .C1 (vbat[1]), .O
       (n_98));
  NR2BHD g1315__5526(.I1 (current_state[0]), .I2 (n_351), .O (tc));
  ND3CHD g1427__6783(.I1 (n_95), .I2 (n_94), .I3 (tempmin[2]), .O
       (n_96));
  ND3CHD g1428__3680(.I1 (n_92), .I2 (n_91), .I3 (ibat[2]), .O (n_93));
  MAO222CHD g1430__1617(.A1 (n_45), .B1 (n_16), .C1 (tempmin[1]), .O
       (n_90));
  ND2CHD g1451__2802(.I1 (n_78), .I2 (n_79), .O (n_89));
  NR2BHD g1314__5122(.I1 (n_246), .I2 (n_351), .O (cc));
  AOI22BHD g1456__8246(.A1 (n_70), .A2 (n_31), .B1 (tpreset[4]), .B2
       (tmax[4]), .O (n_86));
  AOI13BHD g1457__7098(.A1 (n_24), .B1 (n_68), .B2 (tpreset[7]), .B3
       (tmax[7]), .O (n_85));
  MAO222CHD g1425__6131(.A1 (n_33), .B1 (n_14), .C1 (ibat[1]), .O
       (n_84));
  MAOI1CHD g1459__1881(.A1 (tpreset[2]), .A2 (tmax[2]), .B1 (n_41), .B2
       (n_51), .O (n_83));
  OR2EHD g1461__5115(.I1 (n_81), .I2 (n_80), .O (n_82));
  AO222EHD g1494__7482(.A1 (current_state[2]), .A2 (vbat[6]), .B1
       (n_103), .B2 (vpreset[6]), .C1 (n_246), .C2 (vcutoff[6]), .O
       (n_140));
  AO222EHD g1493__4733(.A1 (current_state[2]), .A2 (vbat[7]), .B1
       (n_103), .B2 (vpreset[7]), .C1 (n_246), .C2 (vcutoff[7]), .O
       (n_133));
  NR2CHD g1468__6161(.I1 (n_79), .I2 (n_78), .O (n_154));
  AN2EHD g1453__9315(.I1 (n_77), .I2 (n_76), .O (n_179));
  MXL2CHD g1534__9945(.S (tmax[5]), .A (n_56), .B (tpreset[13]), .OB
       (n_170));
  OAI12CHD g1389__2883(.A1 (n_75), .B1 (n_17), .B2 (tbat[6]), .O
       (n_180));
  MXL2CHD g1529__2346(.S (tmax[2]), .A (n_213), .B (tpreset[10]), .OB
       (n_119));
  OAI12CHD g1404__1666(.A1 (n_74), .B1 (n_21), .B2 (tempmin[6]), .O
       (n_167));
  OAI12CHD g1405__7410(.A1 (n_66), .B1 (n_65), .B2 (ibat[6]), .O
       (n_173));
  OAI22CHD g1533__6417(.A1 (tmax[6]), .A2 (tpreset[14]), .B1 (n_144),
       .B2 (n_73), .O (n_120));
  MOAI1CHD g1496__5477(.A1 (n_248), .A2 (n_72), .B1 (current_state[2]),
       .B2 (vpreset[3]), .O (n_135));
  OAI12CHD g1452__2398(.A1 (n_70), .B1 (tpreset[3]), .B2 (tmax[3]), .O
       (n_71));
  OAI12CHD g1448__5107(.A1 (n_68), .B1 (tpreset[7]), .B2 (tmax[7]), .O
       (n_69));
  ND3CHD g1408__6260(.I1 (n_66), .I2 (n_65), .I3 (ibat[6]), .O (n_67));
  AN2CHD g1312__4319(.I1 (n_63), .I2 (current_state[0]), .O (tmonen));
  MXL2CHD g1535__8428(.S (tmax[3]), .A (n_55), .B (tpreset[11]), .OB
       (n_153));
  AOI12CHD g1536__5526(.A1 (n_63), .B1 (current_state[2]), .B2
       (current_state[1]), .O (n_99));
  OR3B2CHD g1364__6783(.I1 (n_199), .B1 (tpreset[10]), .B2
       (tpreset[11]), .O (n_211));
  ND2DHD g1538__3680(.I1 (n_248), .I2 (n_246), .O (n_62));
  MOAI1CHD g1528__1617(.A1 (tpreset[0]), .A2 (tpreset[1]), .B1
       (tpreset[0]), .B2 (tpreset[1]), .O (n_61));
  AOI22BHD g1506__2802(.A1 (current_state[2]), .A2 (vpreset[0]), .B1
       (1'b1), .B2 (vbat[0]), .O (n_60));
  AOI22BHD g1510__1705(.A1 (current_state[2]), .A2 (vpreset[1]), .B1
       (current_state[1]), .B2 (vbat[1]), .O (n_59));
  INVDHD g1516(.I (n_103), .O (n_58));
  NR2CHD g1522__8246(.I1 (tmax[5]), .I2 (n_56), .O (n_121));
  AOI22BHD g1504__7098(.A1 (current_state[2]), .A2 (vpreset[4]), .B1
       (current_state[1]), .B2 (vbat[4]), .O (n_189));
  ND2CHD g1521__6131(.I1 (tpreset[14]), .I2 (n_73), .O (n_76));
  NR2CHD g1520__1881(.I1 (tmax[3]), .I2 (n_55), .O (n_79));
  MOAI1CHD g1530__5115(.A1 (tpreset[12]), .A2 (tmax[4]), .B1
       (tpreset[12]), .B2 (tmax[4]), .O (n_78));
  MAOI1CHD g1531__7482(.A1 (tpreset[9]), .A2 (tmax[1]), .B1 (tmax[1]),
       .B2 (tpreset[9]), .O (n_80));
  MAOI1CHD g1532__4733(.A1 (tpreset[15]), .A2 (tmax[7]), .B1 (tmax[7]),
       .B2 (tpreset[15]), .O (n_77));
  OR2CHD g1406__6161(.I1 (vbat[7]), .I2 (n_54), .O (n_100));
  AOI22BHD g1502__9315(.A1 (current_state[2]), .A2 (vpreset[5]), .B1
       (current_state[1]), .B2 (vbat[5]), .O (n_138));
  OAI112BHD g1375__2883(.A1 (vbat[7]), .B1 (vbat[6]), .C1 (vbat[5]),
       .C2 (vbat[4]), .O (n_53));
  INVCKDHD g1472(.I (n_51), .O (n_52));
  ND2CHD g1421__2346(.I1 (n_72), .I2 (vcutoff[3]), .O (n_108));
  ND2CHD g1423__1666(.I1 (n_50), .I2 (tempmax[5]), .O (n_128));
  ND2CHD g1431__7410(.I1 (n_49), .I2 (tempmax[3]), .O (n_111));
  ND2CHD g1434__6417(.I1 (n_48), .I2 (tbat[3]), .O (n_95));
  OR2CHD g1435__5477(.I1 (tempmin[5]), .I2 (n_50), .O (n_126));
  ND2CHD g1439__2398(.I1 (n_47), .I2 (iend[3]), .O (n_92));
  OR2CHD g1440__5107(.I1 (ibat[5]), .I2 (n_46), .O (n_131));
  AOI22BHD g1499__6260(.A1 (current_state[2]), .A2 (vpreset[2]), .B1
       (current_state[1]), .B2 (vbat[2]), .O (n_175));
  OAI22CHD g1454__4319(.A1 (tmax[5]), .A2 (tpreset[5]), .B1
       (tpreset[6]), .B2 (tmax[6]), .O (n_182));
  AOI22BHD g1492__8428(.A1 (current_state[2]), .A2 (vpreset[6]), .B1
       (current_state[1]), .B2 (vbat[6]), .O (n_139));
  ND2CHD g1420__5526(.I1 (n_146), .I2 (vcutoff[5]), .O (n_114));
  ND2CHD g1335__6783(.I1 (n_248), .I2 (current_state[2]), .O (n_102));
  AOI22BHD g1491__3680(.A1 (current_state[2]), .A2 (vpreset[7]), .B1
       (current_state[1]), .B2 (vbat[7]), .O (n_134));
  OR2B1CHD g1441__2802(.I1 (tempmin[0]), .B1 (tbat[0]), .O (n_45));
  OR2B1CHD g1438__1705(.I1 (vbat[0]), .B1 (vcutoff[0]), .O (n_44));
  OR2B1CHD g1399__5122(.I1 (iend[7]), .B1 (ibat[7]), .O (n_43));
  ND2CHD g1470__7098(.I1 (tpreset[1]), .I2 (tmax[1]), .O (n_41));
  OR2B1CHD g1401__6131(.I1 (tbat[7]), .B1 (tempmin[7]), .O (n_40));
  AN2B1CHD g1432__1881(.I1 (tempmin[4]), .B1 (tbat[4]), .O (n_39));
  OR2B1CHD g1398__5115(.I1 (vbat[6]), .B1 (vcutoff[6]), .O (n_38));
  OR2B1CHD g1418__7482(.I1 (ibat[4]), .B1 (iend[4]), .O (n_37));
  OR2B1CHD g1419__4733(.I1 (tempmin[4]), .B1 (tbat[4]), .O (n_36));
  NR2CHD g1537__6161(.I1 (current_state[2]), .I2 (current_state[1]), .O
       (n_63));
  OR2B1CHD g1403__9315(.I1 (tbat[7]), .B1 (tempmax[7]), .O (n_75));
  OR2B1CHD g1424__9945(.I1 (tempmin[7]), .B1 (tbat[7]), .O (n_74));
  OR2B1CHD g1422__2883(.I1 (ibat[7]), .B1 (iend[7]), .O (n_66));
  OR2B1CHD g1524__2346(.I1 (tmax[7]), .B1 (tpreset[15]), .O (n_242));
  OR2B1CHD g1525__1666(.I1 (tmax[2]), .B1 (tpreset[10]), .O (n_152));
  OR2B1CHD g1526__7410(.I1 (tmax[4]), .B1 (tpreset[12]), .O (n_169));
  ND2CHD g1518__6417(.I1 (tpreset[4]), .I2 (tpreset[5]), .O (n_151));
  AN2EHD g1539__5477(.I1 (current_state[1]), .I2 (current_state[0]), .O
       (n_103));
  AN2B1CHD g1426__2398(.I1 (tbat[4]), .B1 (tempmax[4]), .O (n_35));
  AN2B1CHD g1436__5107(.I1 (ibat[4]), .B1 (iend[4]), .O (n_34));
  OR2B1CHD g1442__6260(.I1 (ibat[0]), .B1 (iend[0]), .O (n_33));
  ND2DHD g1464__4319(.I1 (tpreset[5]), .I2 (tmax[5]), .O (n_32));
  AN2EHD g1469__8428(.I1 (tpreset[3]), .I2 (tmax[3]), .O (n_31));
  OR2B1CHD g1386__5526(.I1 (tempmax[7]), .B1 (tbat[7]), .O (n_30));
  ND2CHD g1519__6783(.I1 (tpreset[6]), .I2 (tpreset[7]), .O (n_29));
  OR2B1CHD g1396__3680(.I1 (tbat[4]), .B1 (tempmax[4]), .O (n_28));
  OR2B1CHD g1433__1617(.I1 (tbat[0]), .B1 (tempmax[0]), .O (n_27));
  NR2CHD g1467__2802(.I1 (tmax[6]), .I2 (tpreset[6]), .O (n_26));
  AN2B1CHD g1462__1705(.I1 (tmax[0]), .B1 (tpreset[0]), .O (n_25));
  NR2CHD g1463__5122(.I1 (tmax[0]), .I2 (tpreset[8]), .O (n_24));
  ND2DHD g1368__8246(.I1 (tpreset[12]), .I2 (tpreset[13]), .O (n_143));
  OR2EHD g1471__7098(.I1 (tmax[4]), .I2 (tpreset[4]), .O (n_70));
  NR2CHD g1473__6131(.I1 (tmax[2]), .I2 (tpreset[2]), .O (n_51));
  ND2CHD g1474__1881(.I1 (tpreset[8]), .I2 (tmax[0]), .O (n_68));
  OR2B1CHD g1523__5115(.I1 (tmax[1]), .B1 (tpreset[9]), .O (n_118));
  ND2DHD g1367__7482(.I1 (tpreset[8]), .I2 (tpreset[9]), .O (n_199));
  INVCKDHD g1563(.I (tbat[6]), .O (n_21));
  INVCKDHD g1556(.I (tempmax[1]), .O (n_20));
  INVCKDHD g1564(.I (tbat[3]), .O (n_49));
  INVDHD g1571(.I (tpreset[12]), .O (n_212));
  INVCKDHD g1562(.I (vcutoff[2]), .O (n_107));
  INVCKDHD g1558(.I (ibat[3]), .O (n_47));
  INVDHD g1572(.I (tpreset[8]), .O (n_81));
  INVCKDHD g1543(.I (vcutoff[4]), .O (n_113));
  INVDHD g1567(.I (tpreset[13]), .O (n_56));
  INVCKDHD g1544(.I (vcutoff[7]), .O (n_54));
  INVCKDHD g1547(.I (tbat[5]), .O (n_50));
  INVCKDHD g1550(.I (vbat[3]), .O (n_72));
  INVDHD g1574(.I (current_state[0]), .O (n_246));
  INVCKDHD g1541(.I (tempmax[6]), .O (n_17));
  INVCKDHD g1548(.I (tbat[1]), .O (n_16));
  INVCKDHD g1559(.I (tempmax[5]), .O (n_15));
  INVCKDHD g1561(.I (iend[1]), .O (n_14));
  INVCKDHD g1545(.I (vcutoff[1]), .O (n_13));
  INVCKDHD g1540(.I (iend[2]), .O (n_91));
  INVCKDHD g1557(.I (tempmax[2]), .O (n_110));
  INVCKDHD g1555(.I (iend[6]), .O (n_65));
  INVDHD g1553(.I (tpreset[11]), .O (n_55));
  INVCKDHD g1542(.I (tempmin[3]), .O (n_48));
  INVCKDHD g1546(.I (tbat[2]), .O (n_94));
  INVCKDHD g1560(.I (iend[5]), .O (n_46));
  INVDHD g1570(.I (tpreset[10]), .O (n_213));
  INVDHD g1551(.I (tpreset[6]), .O (n_184));
  INVDHD g1569(.I (tpreset[14]), .O (n_144));
  INVCKDHD g1566(.I (tmax[6]), .O (n_73));
  INVCKDHD g1552(.I (vbat[5]), .O (n_146));
  INVDHD g1554(.I (current_state[1]), .O (n_248));
  MXL2CHD g2(.S (n_249), .A (current_state[0]), .B (n_246), .OB
       (n_347));
  XOR2EHD g1594(.I1 (n_352), .I2 (tpreset[2]), .O (n_348));
  AOI13BHD g1595(.A1 (vbat[3]), .B1 (vbat[1]), .B2 (vbat[0]), .B3
       (vbat[2]), .O (n_349));
  AN2B1CHD g1596(.I1 (vbat[6]), .B1 (vcutoff[6]), .O (n_350));
  OR2B1CHD g1597(.I1 (current_state[2]), .B1 (current_state[1]), .O
       (n_351));
  AN2B1CHD g1598(.I1 (tpreset[1]), .B1 (tpreset[0]), .O (n_352));
endmodule

