
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Dec  6 2024 10:25:14 WET (Dec  6 2024 10:25:14 UTC)

// Verification Directory fv/counter4bit_scan 

module counter4bit_scan(clk, enable, count_dir, reset, si, se, so,
     count);
  input clk, enable, count_dir, reset, si, se;
  output so;
  output [3:0] count;
  wire clk, enable, count_dir, reset, si, se;
  wire so;
  wire [3:0] count;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_20, n_22, n_23, n_31, n_32;
  assign count[3] = so;
  QDFZHHD \count_reg[3] (.CK (clk), .D (n_23), .TD (count[2]), .SEL
       (se), .Q (so));
  QDFZKHD \count_reg[2] (.CK (clk), .D (n_22), .TD (count[1]), .SEL
       (se), .Q (count[2]));
  MOAI1CHD g759__2398(.A1 (so), .A2 (n_17), .B1 (so), .B2 (n_32), .O
       (n_23));
  OAI112BHD g758__5107(.A1 (n_20), .B1 (n_16), .C1 (count[2]), .C2
       (n_8), .O (n_22));
  QDFZKHD \count_reg[1] (.CK (clk), .D (n_15), .TD (count[0]), .SEL
       (se), .Q (count[1]));
  QDFZKHD \count_reg[0] (.CK (clk), .D (n_13), .TD (si), .SEL (se), .Q
       (count[0]));
  ND2DHD g762__4319(.I1 (count[2]), .I2 (n_18), .O (n_20));
  AN2EHD g765__8428(.I1 (n_16), .I2 (n_9), .O (n_17));
  OAI12CHD g767__5526(.A1 (n_11), .B1 (n_10), .B2 (n_14), .O (n_15));
  OAI112BHD g766__6783(.A1 (n_7), .B1 (n_12), .C1 (n_5), .C2 (n_14), .O
       (n_18));
  MXL2CHD g768__3680(.S (count[0]), .A (n_1), .B (n_12), .OB (n_13));
  AOI22BHD g770__1617(.A1 (n_10), .A2 (n_6), .B1 (count[1]), .B2 (n_0),
       .O (n_11));
  OR2B1CHD g769__2802(.I1 (n_8), .B1 (count[2]), .O (n_9));
  ND2DHD g772__1705(.I1 (n_3), .I2 (n_6), .O (n_7));
  OR3B1EHD g771__5122(.I1 (n_14), .I2 (count[2]), .B1 (n_5), .O (n_16));
  OR2EHD g773__8246(.I1 (n_4), .I2 (n_3), .O (n_8));
  AN2CHD g775__6131(.I1 (n_14), .I2 (n_4), .O (n_1));
  INVCKDHD g776(.I (n_4), .O (n_6));
  AN2B1CHD g777__1881(.I1 (n_3), .B1 (n_5), .O (n_10));
  OR3B2CHD g778__5115(.I1 (reset), .B1 (enable), .B2 (count_dir), .O
       (n_4));
  INVCKDHD g781(.I (n_0), .O (n_12));
  OR3B1CHD g779__7482(.I1 (count_dir), .I2 (reset), .B1 (enable), .O
       (n_14));
  NR2BHD g783__4733(.I1 (reset), .I2 (enable), .O (n_0));
  ND2CHD g780__6161(.I1 (count[1]), .I2 (count[0]), .O (n_3));
  NR2CHD g782__9315(.I1 (count[1]), .I2 (count[0]), .O (n_5));
  OR2EHD g2(.I1 (n_31), .I2 (n_18), .O (n_32));
  MXL2CHD g3(.S (count[2]), .A (n_4), .B (n_14), .OB (n_31));
endmodule

